/** Duck Force Companion shared backend v0.4.5. API keys verify requests and are never stored. */
const DF_TOOLKIT_VERSION='0.4.5';const DF_FACTION_NAME='Duck Force';
const DF_SHEETS=Object.freeze({SETTINGS:'Settings',RANKS:'RankAccess',USERS:'UserOverrides',POSITIONS:'FactionPositions',NOTICES:'Notices'});
const DF_TOOLS=Object.freeze([['ARMORY','Faction Armory Auditor'],['TRAIN','Company Train Calculator']]);
function setupDuckForceBackend(){const ss=SpreadsheetApp.getActiveSpreadsheet();PropertiesService.getScriptProperties().setProperty('SHEET_ID',ss.getId());const settings=ensureSheet_(ss,DF_SHEETS.SETTINGS,['key','value']);setSetting_(settings,'faction_name',DF_FACTION_NAME);if(!getSetting_(settings,'faction_id'))setSetting_(settings,'faction_id','0');if(!getSetting_(settings,'restrict_faction'))setSetting_(settings,'restrict_faction','true');setSetting_(settings,'schema_version','2');ensureSheet_(ss,DF_SHEETS.RANKS,['rank_name','tool_id','allowed','updated_at','updated_by_id','updated_by_name']);ensureSheet_(ss,DF_SHEETS.USERS,['user_id','tool_id','allowed','updated_at','updated_by_id','updated_by_name']);ensureSheet_(ss,DF_SHEETS.POSITIONS,['faction_id','position_name','abilities_json','updated_at','updated_by_id','updated_by_name']);ensureSheet_(ss,DF_SHEETS.NOTICES,['id','faction_id','title','message','created_at','expires_at','author_id','author_name','active']);return{ok:true,sheet_id:ss.getId(),next:'Set Settings!faction_id to the faction numeric ID, then deploy as a web app.'};}
function doGet(){return json_({ok:true,app:'Duck Force Companion Backend',version:DF_TOOLKIT_VERSION,authenticated_actions:'POST only'});}
function doPost(e){try{const body=JSON.parse((e&&e.postData&&e.postData.contents)||'{}'),action=String(body.action||''),apiKey=String(body.apiKey||'').trim();if(!apiKey)throw new Error('API key required.');const user=verifyFactionUser_(apiKey);if(action==='config'){if(isLeaderOrCoLeader_(user.position)){try{syncFactionPositions_(apiKey,user);}catch(_){}}return json_({ok:true,user:publicUser_(user),can_manage:isLeaderOrCoLeader_(user.position),permissions:readPositionPermissions_(user.faction_id,user.position),rank_rules:readRankRules_(),user_overrides:readUserOverrides_(user.id)});}if(action==='notices')return json_({ok:true,user:publicUser_(user),notices:readActiveNotices_(user.faction_id)});if(action==='positions'||action==='sync_positions'){if(!isLeaderOrCoLeader_(user.position))throw new Error('Leader or Co-leader required.');const positions=syncFactionPositions_(apiKey,user);return json_({ok:true,user:publicUser_(user),positions});}if(action==='post_notice'){if(!canPublishNotice_(user))throw new Error('Announcement Changes permission (or Leader/Co-leader) required.');return json_({ok:true,notice:createNotice_(user,body)});}if(!isLeaderOrCoLeader_(user.position))throw new Error('Leader or Co-leader required.');if(action==='save_rank_rules'){saveRankRules_(String(body.rank_name||''),body.tools||{},user);return json_({ok:true,rank_rules:readRankRules_()});}if(action==='save_user_overrides'){const userId=Number(body.user_id||0);if(!userId)throw new Error('Valid user_id required.');saveUserOverrides_(userId,body.tools||{},user);return json_({ok:true,user_id:userId,user_overrides:readUserOverrides_(userId)});}throw new Error('Unknown action.');}catch(err){return json_({ok:false,error:String(err&&err.message||err)});}}
function verifyFactionUser_(apiKey){const factionData=tornGet_('/user/faction',apiKey),faction=factionData&&factionData.faction;if(!faction)throw new Error('Torn account is not currently in a faction.');const basicData=tornGet_('/user/basic',apiKey),profile=basicData&&basicData.profile||{},settings=settings_(),restrict=String(settings.restrict_faction||'true').toLowerCase()!=='false',expectedId=Number(settings.faction_id||0),expectedName=String(settings.faction_name||DF_FACTION_NAME);if(restrict){if(expectedId&&Number(faction.id)!==expectedId)throw new Error('This backend is restricted to the configured faction.');if(expectedName&&String(faction.name||'').toLowerCase()!==expectedName.toLowerCase())throw new Error('This backend is restricted to the configured faction.');}return{id:Number(profile.id||0),name:String(profile.name||'Unknown'),faction_id:Number(faction.id||0),faction_name:String(faction.name||''),position:String(faction.position||'')};}
function isLeaderOrCoLeader_(position){const n=String(position||'').toLowerCase().replace(/[-_\s]/g,'');return n==='leader'||n==='coleader';}
function syncFactionPositions_(apiKey,actor){const result=tornGet_('/faction/positions',apiKey),positions=Array.isArray(result.positions)?result.positions:[],sheet=db_().getSheetByName(DF_SHEETS.POSITIONS),values=sheet.getDataRange().getValues();for(let i=values.length-1;i>=1;i--)if(Number(values[i][0])===Number(actor.faction_id))sheet.deleteRow(i+1);if(positions.length){const now=new Date(),rows=positions.map(p=>[actor.faction_id,String(p.name||''),JSON.stringify(Array.isArray(p.abilities)?p.abilities:[]),now,actor.id,actor.name]);sheet.getRange(sheet.getLastRow()+1,1,rows.length,rows[0].length).setValues(rows);}return positions;}
function readPositionPermissions_(factionId,positionName){const sheet=db_().getSheetByName(DF_SHEETS.POSITIONS),values=sheet.getDataRange().getValues();for(let i=1;i<values.length;i++){if(Number(values[i][0])!==Number(factionId))continue;if(String(values[i][1]).toLowerCase()!==String(positionName||'').toLowerCase())continue;try{const p=JSON.parse(String(values[i][2]||'[]'));return Array.isArray(p)?p:[];}catch(_){return[];}}return[];}
function hasCachedPermission_(user,permission){if(isLeaderOrCoLeader_(user.position))return true;return readPositionPermissions_(user.faction_id,user.position).some(v=>String(v).toLowerCase()===String(permission).toLowerCase());}
function canPublishNotice_(user){return isLeaderOrCoLeader_(user.position)||hasCachedPermission_(user,'Announcement Changes');}
function createNotice_(user,body){const title=String(body.title||'').trim(),message=String(body.message||'').trim();if(!title||!message)throw new Error('Notice title and message are required.');if(title.length>120)throw new Error('Notice title is too long.');if(message.length>2000)throw new Error('Notice message is too long.');const now=Math.floor(Date.now()/1000);let expiresAt=Number(body.expires_at||0);if(!expiresAt||expiresAt<=now)expiresAt=now+72*3600;const notice={id:Utilities.getUuid(),faction_id:user.faction_id,title,message,created_at:now,expires_at:expiresAt,author_id:user.id,author_name:user.name,active:true};db_().getSheetByName(DF_SHEETS.NOTICES).appendRow([notice.id,notice.faction_id,notice.title,notice.message,notice.created_at,notice.expires_at,notice.author_id,notice.author_name,true]);return notice;}
function readActiveNotices_(factionId){const sheet=db_().getSheetByName(DF_SHEETS.NOTICES),values=sheet.getDataRange().getValues(),now=Math.floor(Date.now()/1000),out=[];for(let i=1;i<values.length;i++){const active=toBoolean_(values[i][8]),expires=Number(values[i][5]||0);if(Number(values[i][1])!==Number(factionId)||!active||(expires&&expires<=now))continue;out.push({id:String(values[i][0]||''),faction_id:Number(values[i][1]||0),title:String(values[i][2]||''),message:String(values[i][3]||''),created_at:Number(values[i][4]||0),expires_at:expires,author_id:Number(values[i][6]||0),author_name:String(values[i][7]||'Leadership')});}out.sort((a,b)=>b.created_at-a.created_at);return out.slice(0,25);}
function saveRankRules_(rankName,tools,actor){rankName=rankName.trim();if(!rankName)throw new Error('rank_name required.');const sheet=db_().getSheetByName(DF_SHEETS.RANKS),rows=sheet.getDataRange().getValues(),now=new Date();DF_TOOLS.forEach(([toolId])=>{if(!(toolId in tools))return;const allowed=Boolean(tools[toolId]);let rowIndex=0;for(let i=1;i<rows.length;i++)if(String(rows[i][0])===rankName&&String(rows[i][1])===toolId){rowIndex=i+1;break;}const values=[rankName,toolId,allowed,now,actor.id,actor.name];if(rowIndex)sheet.getRange(rowIndex,1,1,values.length).setValues([values]);else sheet.appendRow(values);});}
function saveUserOverrides_(userId,tools,actor){const sheet=db_().getSheetByName(DF_SHEETS.USERS),rows=sheet.getDataRange().getValues(),now=new Date();DF_TOOLS.forEach(([toolId])=>{if(!(toolId in tools))return;const allowed=tools[toolId]===null?'':Boolean(tools[toolId]);let rowIndex=0;for(let i=1;i<rows.length;i++)if(Number(rows[i][0])===userId&&String(rows[i][1])===toolId){rowIndex=i+1;break;}const values=[userId,toolId,allowed,now,actor.id,actor.name];if(rowIndex)sheet.getRange(rowIndex,1,1,values.length).setValues([values]);else sheet.appendRow(values);});}
function readRankRules_(){const sheet=db_().getSheetByName(DF_SHEETS.RANKS),values=sheet.getDataRange().getValues(),out={};for(let i=1;i<values.length;i++){const rank=String(values[i][0]||''),tool=String(values[i][1]||'');if(!rank||!tool)continue;if(!out[rank])out[rank]={};out[rank][tool]=toBoolean_(values[i][2]);}return out;}
function readUserOverrides_(userId){const sheet=db_().getSheetByName(DF_SHEETS.USERS),values=sheet.getDataRange().getValues(),out={};for(let i=1;i<values.length;i++){if(Number(values[i][0])!==Number(userId))continue;const tool=String(values[i][1]||'');if(!tool)continue;const raw=values[i][2];out[tool]=raw===''?null:toBoolean_(raw);}return out;}
function settings_(){const sheet=db_().getSheetByName(DF_SHEETS.SETTINGS),values=sheet.getDataRange().getValues(),out={};for(let i=1;i<values.length;i++){const key=String(values[i][0]||'');if(key)out[key]=values[i][1];}return out;}
function setSetting_(sheet,key,value){const values=sheet.getDataRange().getValues();for(let i=1;i<values.length;i++)if(String(values[i][0])===key){sheet.getRange(i+1,2).setValue(value);return;}sheet.appendRow([key,value]);}
function getSetting_(sheet,key){const values=sheet.getDataRange().getValues();for(let i=1;i<values.length;i++)if(String(values[i][0])===key)return values[i][1];return'';}
function ensureSheet_(ss,name,headers){let sheet=ss.getSheetByName(name);if(!sheet)sheet=ss.insertSheet(name);if(sheet.getLastRow()===0)sheet.appendRow(headers);return sheet;}
function db_(){const id=PropertiesService.getScriptProperties().getProperty('SHEET_ID');if(!id)throw new Error('Backend is not configured. Run setupDuckForceBackend() first.');return SpreadsheetApp.openById(id);}
function tornGet_(path,apiKey){const url='https://api.torn.com/v2'+path+'?key='+encodeURIComponent(apiKey),response=UrlFetchApp.fetch(url,{method:'get',muteHttpExceptions:true,headers:{'User-Agent':'DuckForceCompanion-Backend/'+DF_TOOLKIT_VERSION}});let data;try{data=JSON.parse(response.getContentText());}catch(_){throw new Error('Unreadable Torn API response.');}if(data&&data.error)throw new Error(data.error.error||('Torn API error '+data.error.code));if(response.getResponseCode()<200||response.getResponseCode()>=300)throw new Error('Torn API HTTP '+response.getResponseCode());return data;}
function publicUser_(user){return{id:user.id,name:user.name,faction_id:user.faction_id,faction_name:user.faction_name,position:user.position};}
function toBoolean_(value){return value===true||String(value).toLowerCase()==='true'||Number(value)===1;}
function json_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);}
