/**
 * TornFCA Community Backend v1.
 * Deploy this file as its OWN Google Apps Script web app, separate from AccessBackend.gs.
 * Torn API keys are used only to verify the current request and are never written to Sheets/Properties/Cache.
 * Cached identity is keyed only by a SHA-256 fingerprint of the API key.
 *
 * Required Script Properties after setup:
 *   COMMUNITY_SHEET_ID (setup writes this automatically)
 * Optional FCM HTTP v1 properties (server-side only; NEVER compile into Android):
 *   FIREBASE_PROJECT_ID, FIREBASE_CLIENT_EMAIL, FIREBASE_PRIVATE_KEY
 */
const TC_VERSION='1.0.0';
const TC_CHAT='ChatMessages';
const TC_DEVICES='PushDevices';
const TC_CHANNELS=['general','war','oc','leadership'];

function setupTornFcaCommunityBackend(){const ss=SpreadsheetApp.getActiveSpreadsheet();PropertiesService.getScriptProperties().setProperty('COMMUNITY_SHEET_ID',ss.getId());tcEnsureSheet_(ss,TC_CHAT,['id','faction_id','channel','author_id','author_name','message','created_at']);tcEnsureSheet_(ss,TC_DEVICES,['token_hash','faction_id','player_id','token','preferences_json','platform','updated_at','active']);return{ok:true,sheet_id:ss.getId(),schema_version:1,next:'Deploy this Apps Script as a web app. Store Firebase service-account values only in Script Properties if cloud push is desired.'};}
function doGet(){return tcJson_({ok:true,app:'TornFCA Community Backend',version:TC_VERSION,authenticated_actions:'POST only'});}
function doPost(e){try{const body=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');const action=String(body.action||'');const key=String(body.apiKey||'').trim();if(!key)throw new Error('API key required.');const user=tcVerifyUser_(key);if(action==='config')return tcJson_({ok:true,user:tcPublicUser_(user),capabilities:{chat:true,push:tcFirebaseConfigured_()}});if(action==='chat_list')return tcJson_({ok:true,user:tcPublicUser_(user),messages:tcReadChat_(user,body)});if(action==='chat_send')return tcJson_({ok:true,message:tcSendChat_(user,body)});if(action==='push_register')return tcJson_({ok:true,device:tcRegisterDevice_(user,body)});if(action==='push_unregister')return tcJson_({ok:true,removed:tcUnregisterDevice_(user,body)});if(action==='push_test'){tcRate_(user.id,'push_test',10);return tcJson_({ok:true,push:tcPushToPlayer_(user.faction_id,user.id,'personal','TornFCA cloud push is ready','This device is registered for TornFCA push notifications.',{})});}if(action==='announcement_push'){if(!tcCanAnnounce_(key,user))throw new Error('Announcement Changes permission is required.');const title=String(body.title||'Faction update').trim().slice(0,120),message=String(body.message||'').trim().slice(0,2000);if(!message)throw new Error('Announcement message required.');return tcJson_({ok:true,push:tcPushToFaction_(user.faction_id,0,'faction',title,message,{})});}throw new Error('Unknown action.');}catch(err){return tcJson_({ok:false,error:String(err&&err.message||err)});}}

function tcVerifyUser_(apiKey){const fp=tcHash_(apiKey),cache=CacheService.getScriptCache(),ck='identity:'+fp;const cached=cache.get(ck);if(cached){try{return JSON.parse(cached);}catch(_){} }const factionData=tcTornGet_('/user/faction',apiKey),faction=factionData&&factionData.faction;if(!faction||!Number(faction.id||0))throw new Error('Torn account is not currently in a faction.');const basic=tcTornGet_('/user/basic',apiKey),profile=basic&&basic.profile||{};const user={id:Number(profile.id||0),name:String(profile.name||'Unknown'),faction_id:Number(faction.id||0),faction_name:String(faction.name||''),position:String(faction.position||'')};if(!user.id)throw new Error('Unable to verify Torn player identity.');cache.put(ck,JSON.stringify(user),90);return user;}
function tcTornGet_(path,key){const joiner=String(path).indexOf('?')>=0?'&':'?';const response=UrlFetchApp.fetch('https://api.torn.com/v2'+path+joiner+'key='+encodeURIComponent(key),{method:'get',muteHttpExceptions:true,headers:{'User-Agent':'TornFCA-Community/'+TC_VERSION}});let data;try{data=JSON.parse(response.getContentText());}catch(_){throw new Error('Unreadable Torn API response.');}if(data&&data.error)throw new Error(data.error.error||('Torn API error '+data.error.code));if(response.getResponseCode()<200||response.getResponseCode()>=300)throw new Error('Torn API HTTP '+response.getResponseCode());return data;}
function tcPublicUser_(u){return{id:u.id,name:u.name,faction_id:u.faction_id,faction_name:u.faction_name,position:u.position};}
function tcLeader_(position){const n=String(position||'').toLowerCase().replace(/[-_\s]/g,'');return n==='leader'||n==='coleader';}
function tcCanAnnounce_(apiKey,user){if(tcLeader_(user.position))return true;const data=tcTornGet_('/faction/positions',apiKey),positions=data&&data.positions;if(!Array.isArray(positions))return false;const current=String(user.position||'').trim().toLowerCase();for(let i=0;i<positions.length;i++){const p=positions[i]||{};if(String(p.name||'').trim().toLowerCase()!==current)continue;const abilities=Array.isArray(p.abilities)?p.abilities:[];return abilities.some(a=>String(a||'').trim().toLowerCase()==='announcement changes');}return false;}
function tcChannel_(user,raw){const c=String(raw||'general').toLowerCase();if(TC_CHANNELS.indexOf(c)<0)throw new Error('Unknown chat channel.');if(c==='leadership'&&!tcLeader_(user.position))throw new Error('Leadership chat is restricted to Leader/Co-leader.');return c;}
function tcReadChat_(user,body){tcRate_(user.id,'chat_list',2);const channel=tcChannel_(user,body.channel),sheet=tcDb_().getSheetByName(TC_CHAT),values=sheet.getDataRange().getValues(),out=[];for(let i=Math.max(1,values.length-600);i<values.length;i++){if(Number(values[i][1])!==user.faction_id||String(values[i][2])!==channel)continue;out.push({id:String(values[i][0]||''),faction_id:Number(values[i][1]||0),channel:String(values[i][2]||'general'),author_id:Number(values[i][3]||0),author_name:String(values[i][4]||'Member'),message:String(values[i][5]||''),created_at:Number(values[i][6]||0)});}out.sort((a,b)=>a.created_at-b.created_at);return out.slice(-75);}
function tcSendChat_(user,body){tcRate_(user.id,'chat_send',2);const channel=tcChannel_(user,body.channel),message=String(body.message||'').trim();if(!message)throw new Error('Message required.');if(message.length>1000)throw new Error('Messages are limited to 1,000 characters.');const row={id:Utilities.getUuid(),faction_id:user.faction_id,channel:channel,author_id:user.id,author_name:user.name,message:message,created_at:Math.floor(Date.now()/1000)};tcDb_().getSheetByName(TC_CHAT).appendRow([row.id,row.faction_id,row.channel,row.author_id,tcSafe_(row.author_name),tcSafe_(row.message),row.created_at]);if(channel!=='leadership')tcPushToFaction_(user.faction_id,user.id,'chat',user.name+' • '+channel,message,{channel:channel,author_id:String(user.id)});return row;}

function tcRegisterDevice_(user,body){tcRate_(user.id,'push_register',5);const token=String(body.token||'').trim();if(token.length<20||token.length>4096)throw new Error('Valid FCM token required.');let prefs=String(body.preferences||'{}');if(prefs.length>4000)prefs='{}';const platform=String(body.platform||'android').slice(0,40),hash=tcHash_(token),sheet=tcDb_().getSheetByName(TC_DEVICES),values=sheet.getDataRange().getValues(),now=Math.floor(Date.now()/1000);for(let i=1;i<values.length;i++){if(String(values[i][0])!==hash)continue;sheet.getRange(i+1,1,1,8).setValues([[hash,user.faction_id,user.id,tcSafe_(token),tcSafe_(prefs),platform,now,true]]);return{registered:true,updated:true};}sheet.appendRow([hash,user.faction_id,user.id,tcSafe_(token),tcSafe_(prefs),platform,now,true]);return{registered:true,updated:false};}
function tcUnregisterDevice_(user,body){const hash=tcHash_(String(body.token||'')),sheet=tcDb_().getSheetByName(TC_DEVICES),values=sheet.getDataRange().getValues();let removed=0;for(let i=1;i<values.length;i++){if(String(values[i][0])!==hash||Number(values[i][1])!==user.faction_id||Number(values[i][2])!==user.id)continue;sheet.getRange(i+1,8).setValue(false);removed++;}return removed;}
function tcDevices_(factionId,playerId,type,excludePlayer){const sheet=tcDb_().getSheetByName(TC_DEVICES),values=sheet.getDataRange().getValues(),out=[],cutoff=Math.floor(Date.now()/1000)-90*86400;for(let i=1;i<values.length;i++){if(!tcBool_(values[i][7])||Number(values[i][1])!==Number(factionId)||Number(values[i][6]||0)<cutoff)continue;const pid=Number(values[i][2]||0);if(playerId&&pid!==Number(playerId))continue;if(excludePlayer&&pid===Number(excludePlayer))continue;let prefs={};try{prefs=JSON.parse(String(values[i][4]||'{}'));}catch(_){}if(prefs.master===false)continue;if(type&&prefs[type]===false)continue;out.push({token:String(values[i][3]||''),player_id:pid});if(out.length>=100)break;}return out;}

function tcPushToFaction_(factionId,excludePlayer,type,title,body,data){return tcPush_(tcDevices_(factionId,0,type,excludePlayer),factionId,type,title,body,data);}
function tcPushToPlayer_(factionId,playerId,type,title,body,data){return tcPush_(tcDevices_(factionId,playerId,type,0),factionId,type,title,body,data);}
function tcPush_(devices,factionId,type,title,body,data){if(!tcFirebaseConfigured_())return{configured:false,sent:0,failed:0};let access;try{access=tcFirebaseAccessToken_();}catch(err){return{configured:true,sent:0,failed:devices.length,error:String(err&&err.message||err)};}let sent=0,failed=0;devices.forEach(d=>{try{const payload={type:String(type||'personal'),title:String(title||'TornFCA'),body:String(body||''),faction_id:String(factionId||0)};Object.keys(data||{}).forEach(k=>payload[k]=String(data[k]));const project=PropertiesService.getScriptProperties().getProperty('FIREBASE_PROJECT_ID');const response=UrlFetchApp.fetch('https://fcm.googleapis.com/v1/projects/'+encodeURIComponent(project)+'/messages:send',{method:'post',muteHttpExceptions:true,contentType:'application/json',headers:{Authorization:'Bearer '+access},payload:JSON.stringify({message:{token:d.token,data:payload,android:{priority:'high'}}})});if(response.getResponseCode()>=200&&response.getResponseCode()<300)sent++;else failed++;}catch(_){failed++;}});return{configured:true,sent:sent,failed:failed};}
function tcFirebaseConfigured_(){const p=PropertiesService.getScriptProperties();return!!(p.getProperty('FIREBASE_PROJECT_ID')&&p.getProperty('FIREBASE_CLIENT_EMAIL')&&p.getProperty('FIREBASE_PRIVATE_KEY'));}
function tcFirebaseAccessToken_(){const cache=CacheService.getScriptCache(),cached=cache.get('firebase_access_token');if(cached)return cached;const p=PropertiesService.getScriptProperties(),email=p.getProperty('FIREBASE_CLIENT_EMAIL'),privateKey=String(p.getProperty('FIREBASE_PRIVATE_KEY')||'').replace(/\\n/g,'\n');if(!email||!privateKey)throw new Error('Firebase service account is not configured.');const now=Math.floor(Date.now()/1000),header=tcB64_(JSON.stringify({alg:'RS256',typ:'JWT'})),claim=tcB64_(JSON.stringify({iss:email,scope:'https://www.googleapis.com/auth/firebase.messaging',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600})),unsigned=header+'.'+claim,signature=Utilities.computeRsaSha256Signature(unsigned,privateKey),jwt=unsigned+'.'+Utilities.base64EncodeWebSafe(signature).replace(/=+$/,'');const response=UrlFetchApp.fetch('https://oauth2.googleapis.com/token',{method:'post',muteHttpExceptions:true,payload:{grant_type:'urn:ietf:params:oauth-type:jwt-bearer',assertion:jwt}});let data;try{data=JSON.parse(response.getContentText());}catch(_){throw new Error('Unreadable Firebase OAuth response.');}if(response.getResponseCode()<200||response.getResponseCode()>=300||!data.access_token)throw new Error(data.error_description||'Firebase OAuth failed.');cache.put('firebase_access_token',String(data.access_token),Math.max(60,Math.min(3300,Number(data.expires_in||3600)-60)));return String(data.access_token);}
function tcB64_(value){return Utilities.base64EncodeWebSafe(value,Utilities.Charset.UTF_8).replace(/=+$/,'');}

function tcRate_(playerId,action,seconds){const cache=CacheService.getScriptCache(),key='rate:'+playerId+':'+action;if(cache.get(key))throw new Error('Please wait a moment before trying again.');cache.put(key,'1',Math.max(1,seconds));}
function tcHash_(value){const bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(value||''),Utilities.Charset.UTF_8);return bytes.map(b=>('0'+((b<0?b+256:b)&255).toString(16)).slice(-2)).join('');}
function tcDb_(){const id=PropertiesService.getScriptProperties().getProperty('COMMUNITY_SHEET_ID');if(!id)throw new Error('Community backend is not configured. Run setupTornFcaCommunityBackend() first.');return SpreadsheetApp.openById(id);}
function tcEnsureSheet_(ss,name,headers){let sheet=ss.getSheetByName(name);if(!sheet)sheet=ss.insertSheet(name);if(sheet.getLastRow()===0)sheet.appendRow(headers);return sheet;}
function tcSafe_(value){const text=String(value==null?'':value);return/^[=+\-@]/.test(text)?"'"+text:text;}
function tcBool_(value){return value===true||String(value).toLowerCase()==='true'||Number(value)===1;}
function tcJson_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);}
