package com.matthayesego.duckforcetoolkit;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.view.Gravity;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import org.json.JSONArray;
import org.json.JSONObject;

import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Leadership sale advisor for Ranked War cache rewards. No trades are executed by TornFCA. */
public class CacheMarketAdvisorActivity extends Activity {
    private static final int BG=Color.rgb(5,8,12),PANEL=Color.rgb(12,18,26),PANEL2=Color.rgb(8,13,20),BORDER=Color.rgb(36,47,61),TEXT=Color.rgb(246,248,251),MUTED=Color.rgb(145,155,169),GOLD=Color.rgb(241,190,86),BLUE=Color.rgb(82,153,235),GREEN=Color.rgb(76,190,102),RED=Color.rgb(239,88,82),PURPLE=Color.rgb(170,115,238);
    private static final Pattern PERCENT=Pattern.compile("(?i)(\\d{2,3}(?:\\.\\d+)?)\\s*%");
    private static final Pattern SHORT_MONEY=Pattern.compile("(?i)\\$?\\s*([0-9]+(?:\\.[0-9]+)?)\\s*([kmb])\\b");
    private static final Pattern LONG_MONEY=Pattern.compile("\\$?\\s*([0-9][0-9,]{5,})");
    private SecureApiKeyStore keyStore;private String key,position="Member",factionName="Faction";private int factionId;
    private JSONArray history=new JSONArray();

    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);keyStore=new SecureApiKeyStore(this);key=keyStore.load();position=getIntent().getStringExtra(DeveloperConsoleActivity.EXTRA_POSITION);if(position==null)position="Member";factionId=getIntent().getIntExtra(FactionOpsActivity.EXTRA_FACTION_ID,0);String f=getIntent().getStringExtra(FactionOpsActivity.EXTRA_FACTION_NAME);if(f!=null&&!f.isBlank())factionName=f;if(!AccessPolicy.isLeaderPosition(position)){renderError("Cache Market Advisor is restricted to faction leadership.");return;}if(key==null||key.isBlank()){renderError("Reconnect your Torn API key first.");return;}showLoading("Loading completed Ranked Wars…");loadHistory();}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private GradientDrawable rounded(int fill,int stroke,int radius){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}
    private GradientDrawable gradient(int a,int b,int stroke,int radius){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});d.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}
    private TextView text(String value,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setLineSpacing(0,1.08f);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private TextView eye(String value,int color){TextView t=text(value,9.5f,color,true);t.setLetterSpacing(.12f);return t;}
    private Button button(String value,int accent){Button b=new Button(this);b.setText(value);b.setAllCaps(false);b.setTextColor(TEXT);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(rounded(PANEL2,accent,13));return b;}
    private LinearLayout card(int accent){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(16),dp(18),dp(16));c.setBackground(gradient(PANEL,PANEL2,accent==Color.TRANSPARENT?BORDER:accent,20));return c;}
    private void add(LinearLayout root,LinearLayout c){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.bottomMargin=dp(11);root.addView(c,p);}
    @SuppressWarnings("deprecation") private ScrollView shell(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setClipToPadding(false);s.setBackgroundColor(BG);int l=dp(18),t=dp(14),r=dp(18),bb=dp(28);s.setPadding(l,t,r,bb);s.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(l+i.getSystemWindowInsetLeft(),t+i.getSystemWindowInsetTop(),r+i.getSystemWindowInsetRight(),bb+i.getSystemWindowInsetBottom());return i;});return s;}
    private LinearLayout root(ScrollView s){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);s.addView(r,new ScrollView.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));return r;}
    private void header(LinearLayout r,String sub){Button back=button("← Leadership",BORDER);back.setOnClickListener(v->finish());r.addView(back,new LinearLayout.LayoutParams(dp(150),dp(44)));TextView e=eye("LEADERSHIP • FINANCE & ASSETS",GOLD);LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);ep.topMargin=dp(18);r.addView(e,ep);r.addView(text("RW Cache Market Advisor",29,TEXT,true));TextView st=text(factionName+" • "+sub,13,MUTED,false);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);sp.topMargin=dp(5);sp.bottomMargin=dp(16);r.addView(st,sp);}
    private void finish(ScrollView s){setContentView(s);s.requestApplyInsets();}
    private void showLoading(String msg){ScrollView s=shell();LinearLayout r=root(s);header(r,"Loading");LinearLayout c=card(BORDER);c.addView(eye("MARKET SCAN",GOLD));c.addView(text(msg,18,TEXT,true));add(r,c);finish(s);}
    private void renderError(String msg){runOnUiThread(()->{ScrollView s=shell();LinearLayout r=root(s);header(r,"Unavailable");LinearLayout c=card(RED);c.addView(text("Unable to load advisor",18,TEXT,true));c.addView(text(msg,13,MUTED,false));add(r,c);finish(s);});}

    private void loadHistory(){new Thread(()->{try{if(factionId<=0){JSONObject f=TornApiClient.getJson("/user/faction",key).optJSONObject("faction");if(f!=null)factionId=f.optInt("id",0);}JSONArray h=TornApiClient.getJson("/faction/"+factionId+"/rankedwars?limit=10",key).optJSONArray("rankedwars");history=h==null?new JSONArray():h;runOnUiThread(this::renderWarPicker);}catch(Exception e){renderError(e.getMessage()==null?"Unable to load Ranked War history.":e.getMessage());}},"TornFCA-CacheWars").start();}
    private void renderWarPicker(){ScrollView s=shell();LinearLayout r=root(s);header(r,"Choose the war whose cache rewards you want to value");LinearLayout info=card(BLUE);info.addView(text("What this compares",18,TEXT,true));info.addView(text("TornFCA reads official war reward items, current Item Market asks, the official specialized-bazaar directory, and recent public forum threads that appear to advertise cache buying. Forum prices are parsed as leads and must be verified before trading.",12.5f,MUTED,false));add(r,info);if(history.length()==0){add(r,messageCard("No completed Ranked Wars returned.",BORDER));finish(s);return;}for(int i=0;i<history.length();i++){JSONObject w=history.optJSONObject(i);if(w==null)continue;int id=w.optInt("id",0);JSONArray fs=w.optJSONArray("factions");String opp="Opponent";int ours=0,theirs=0;for(int j=0;fs!=null&&j<fs.length();j++){JSONObject f=fs.optJSONObject(j);if(f==null)continue;if(f.optInt("id",0)==factionId)ours=f.optInt("score",0);else{opp=f.optString("name",opp);theirs=f.optInt("score",0);}}LinearLayout c=card(Color.TRANSPARENT);c.addView(eye("WAR #"+id,GOLD));c.addView(text("vs "+opp,18,TEXT,true));c.addView(text("Final "+ours+" – "+theirs,12.5f,MUTED,false));Button use=button("Load Cache Rewards",GOLD);LinearLayout.LayoutParams up=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(44));up.topMargin=dp(9);c.addView(use,up);use.setOnClickListener(v->loadReport(id));add(r,c);}finish(s);}
    private LinearLayout messageCard(String msg,int accent){LinearLayout c=card(accent);c.addView(text(msg,16,TEXT,true));return c;}
    private void loadReport(int warId){showLoading("Loading official rewards for war #"+warId+"…");new Thread(()->{try{JSONObject report=TornApiClient.getJson("/faction/"+warId+"/rankedwarreport",key).optJSONObject("rankedwarreport");if(report==null)throw new Exception("The war report was empty.");JSONObject ours=findFaction(report);JSONArray items=ours==null?null:ours.optJSONObject("rewards")==null?null:ours.optJSONObject("rewards").optJSONArray("items");JSONArray safe=items==null?new JSONArray():items;runOnUiThread(()->renderRewards(warId,safe));}catch(Exception e){renderError(e.getMessage()==null?"Unable to load war rewards.":e.getMessage());}},"TornFCA-CacheRewards").start();}
    private JSONObject findFaction(JSONObject report){JSONArray fs=report.optJSONArray("factions");for(int i=0;fs!=null&&i<fs.length();i++){JSONObject f=fs.optJSONObject(i);if(f!=null&&f.optInt("id",0)==factionId)return f;}return null;}
    private void renderRewards(int warId,JSONArray items){ScrollView s=shell();LinearLayout r=root(s);header(r,"War #"+warId+" reward items");if(items.length()==0){LinearLayout n=card(BORDER);n.addView(text("No item rewards returned for your faction in this report.",16,TEXT,true));add(r,n);}for(int i=0;i<items.length();i++){JSONObject item=items.optJSONObject(i);if(item==null)continue;int id=item.optInt("id",0),qty=item.optInt("quantity",0);String name=item.optString("name","Item #"+id);LinearLayout c=card(GOLD);c.addView(eye("REWARD ITEM • QTY "+qty,GOLD));c.addView(text(name,20,TEXT,true));Button scan=button("Compare Current Sale Options",GREEN);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(46));sp.topMargin=dp(10);c.addView(scan,sp);scan.setOnClickListener(v->scanItem(id,name,qty,warId));add(r,c);}Button back=button("Choose Another War",BORDER);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(46));bp.bottomMargin=dp(10);r.addView(back,bp);back.setOnClickListener(v->renderWarPicker());finish(s);}

    private void scanItem(int itemId,String name,int qty,int warId){showLoading("Comparing "+name+" across official market data and recent forum leads…");new Thread(()->{try{JSONObject marketRoot=TornApiClient.getJson("/market/"+itemId+"/itemmarket?limit=100",key);JSONObject market=marketRoot.optJSONObject("itemmarket");if(market==null)throw new Exception("Item Market data was empty.");JSONObject item=market.optJSONObject("item");long average=item==null?0:item.optLong("average_price",0);JSONArray listings=market.optJSONArray("listings");long lowest=lowestAsk(listings);long cacheTs=market.optLong("cache_timestamp",0);JSONArray bazaarRoot=TornApiClient.getJson("/market/"+itemId+"/bazaar",key).optJSONObject("bazaar")==null?new JSONArray():TornApiClient.getJson("/market/"+itemId+"/bazaar",key).optJSONObject("bazaar").optJSONArray("specialized");if(bazaarRoot==null)bazaarRoot=new JSONArray();List<ForumLead> leads=scanForum(name,average);JSONArray bazaars=bazaarRoot;runOnUiThread(()->renderComparison(itemId,name,qty,warId,average,lowest,cacheTs,listings,bazaars,leads));}catch(Exception e){renderError(e.getMessage()==null?"Unable to compare current sale options.":e.getMessage());}},"TornFCA-CacheCompare").start();}
    private long lowestAsk(JSONArray listings){long min=Long.MAX_VALUE;for(int i=0;listings!=null&&i<listings.length();i++){JSONObject x=listings.optJSONObject(i);if(x==null)continue;long p=x.optLong("price",0);if(p>0&&p<min)min=p;}return min==Long.MAX_VALUE?0:min;}

    private List<ForumLead> scanForum(String itemName,long average){List<ForumLead> out=new ArrayList<>();try{long from=System.currentTimeMillis()/1000L-30L*86400L;JSONArray threads=TornApiClient.getJson("/forum/threads?limit=100&sort=DESC&from="+from,key).optJSONArray("threads");String needle=itemName.toLowerCase(Locale.US).replace(" cache","").trim();int inspected=0;for(int i=0;threads!=null&&i<threads.length()&&inspected<8;i++){JSONObject t=threads.optJSONObject(i);if(t==null)continue;String title=t.optString("title","");String lower=title.toLowerCase(Locale.US);boolean relevant=lower.contains("cache")&&(lower.contains("rw")||lower.contains("ranked")||lower.contains("buy")||lower.contains(needle));if(!relevant)continue;int id=t.optInt("id",0);if(id<=0)continue;inspected++;JSONObject thread=TornApiClient.getJson("/forum/"+id+"/thread?strip_tags=true",key).optJSONObject("thread");if(thread==null)continue;String content=thread.optString("content",thread.optString("content_raw",""));String all=(title+" "+content).toLowerCase(Locale.US);if(!(all.contains("buy")||all.contains("buying")||all.contains("pay")||all.contains("trader")))continue;boolean itemMatch=all.contains(needle)||all.contains("rw cache")||all.contains("ranked war cache")||all.contains("all cache")||all.contains("all rw");if(!itemMatch)continue;long quote=parseQuote(content,average);JSONObject author=thread.optJSONObject("author");if(author==null)author=t.optJSONObject("author");String user=author==null?"Forum trader":author.optString("username","Forum trader");int userId=author==null?0:author.optInt("id",0);long time=thread.optLong("last_post_time",thread.optLong("first_post_time",t.optLong("last_post_time",t.optLong("first_post_time",0))));out.add(new ForumLead(id,t.optInt("forum_id",0),user,userId,title,quote,time));}}catch(Exception ignored){}return out;}
    private long parseQuote(String content,long average){if(content==null)return 0;long best=0;Matcher pct=PERCENT.matcher(content);while(pct.find()){try{double p=Double.parseDouble(pct.group(1));if(p>=50&&p<=110&&average>0)best=Math.max(best,Math.round(average*p/100d));}catch(Exception ignored){}}Matcher sm=SHORT_MONEY.matcher(content);while(sm.find()){try{double v=Double.parseDouble(sm.group(1));String unit=sm.group(2).toLowerCase(Locale.US);double mul="b".equals(unit)?1_000_000_000d:"m".equals(unit)?1_000_000d:1_000d;long x=Math.round(v*mul);if(plausible(x,average))best=Math.max(best,x);}catch(Exception ignored){}}Matcher lm=LONG_MONEY.matcher(content);while(lm.find()){try{long x=Long.parseLong(lm.group(1).replace(",",""));if(plausible(x,average))best=Math.max(best,x);}catch(Exception ignored){}}return best;}
    private boolean plausible(long x,long average){if(x<=0)return false;if(average<=0)return x>=1_000_000;return x>=Math.round(average*.45)&&x<=Math.round(average*1.5);}

    private void renderComparison(int itemId,String name,int qty,int warId,long average,long lowest,long cacheTs,JSONArray listings,JSONArray bazaars,List<ForumLead> leads){ScrollView s=shell();LinearLayout r=root(s);header(r,name+" • quantity "+qty);long bestForum=0;ForumLead bestLead=null;for(ForumLead l:leads)if(l.quote>bestForum){bestForum=l.quote;bestLead=l;}String recommendation;if(bestLead!=null&&bestForum>lowest&&lowest>0)recommendation="Best priced lead found: "+bestLead.user+" at approximately "+money(bestForum)+" each. Verify the forum offer before trading.";else if(lowest>0)recommendation="Current Item Market floor is "+money(lowest)+" each. No parsed forum lead clearly beats that gross asking-price reference.";else if(bestLead!=null)recommendation="Best priced forum lead found: "+bestLead.user+" at approximately "+money(bestForum)+" each. Verify before trading.";else recommendation="No directly comparable priced offer was found in this scan.";
        LinearLayout best=card(GREEN);best.addView(eye("CURRENT RECOMMENDATION",GREEN));best.addView(text(recommendation,17,TEXT,true));best.addView(text("This is decision support only. Item Market figures are asking prices, not guaranteed instant-sale proceeds, and TornFCA never initiates a trade or sale.",11.5f,MUTED,false));add(r,best);
        LinearLayout m=card(BLUE);m.addView(eye("ITEM MARKET • OFFICIAL TORN DATA",BLUE));m.addView(text("Average price: "+money(average)+"\nLowest current ask: "+(lowest>0?money(lowest):"Unavailable")+"\nListings scanned: "+(listings==null?0:listings.length())+"\nMarket cache timestamp: "+formatTime(cacheTs)+" ("+age(cacheTs)+" ago)",13,TEXT,false));add(r,m);
        LinearLayout bz=card(GOLD);bz.addView(eye("SPECIALIZED BAZAAR DIRECTORY",GOLD));bz.addView(text(bazaars.length()+" specialized bazaars returned for this item. Torn's public bazaar directory does not expose per-item listing prices here, so TornFCA does not invent a price comparison.",12.5f,MUTED,false));for(int i=0;i<Math.min(5,bazaars.length());i++){JSONObject b=bazaars.optJSONObject(i);if(b==null)continue;bz.addView(text((b.optBoolean("is_open",false)?"OPEN • ":"CLOSED • ")+b.optString("name","Bazaar")+" ["+b.optInt("id",0)+"] • "+b.optInt("weekly_customers",0)+" weekly customers",11.5f,TEXT,false));}add(r,bz);
        LinearLayout forum=card(PURPLE);forum.addView(eye("RECENT FORUM LEADS • LAST 30 DAYS",PURPLE));if(leads.isEmpty())forum.addView(text("No recent public thread matched the cache-buying filters in this scan.",12.5f,MUTED,false));else for(ForumLead l:leads){String q=l.quote>0?"Parsed quote ≈ "+money(l.quote)+" each":"Relevant thread • no safe price parsed";TextView row=text(l.user+(l.userId>0?" ["+l.userId+"]":"")+"\n"+q+" • "+age(l.time)+" ago\n“"+trim(l.title,80)+"”",12.5f,l.quote>0?TEXT:MUTED,false);row.setPadding(0,dp(8),0,dp(5));row.setOnClickListener(v->openForum(l));forum.addView(row);}forum.addView(text("Tap a forum lead to verify the live thread. Parsed percentages/amounts are heuristics, not contractual offers.",10.5f,MUTED,false));add(r,forum);
        Button refresh=button("Refresh This Comparison",GREEN);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(48));rp.bottomMargin=dp(8);r.addView(refresh,rp);refresh.setOnClickListener(v->scanItem(itemId,name,qty,warId));Button rewards=button("Back to War Rewards",BORDER);LinearLayout.LayoutParams wp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(46));wp.bottomMargin=dp(10);r.addView(rewards,wp);rewards.setOnClickListener(v->loadReport(warId));finish(s);}
    private void openForum(ForumLead l){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.torn.com/forums.php#/p=threads&f="+l.forumId+"&t="+l.threadId+"&b=0&a=0")));}catch(Exception ignored){}}
    private String money(long v){return v<=0?"Unavailable":"$"+NumberFormat.getIntegerInstance(Locale.US).format(v);}
    private String formatTime(long ts){if(ts<=0)return"Unknown";return new SimpleDateFormat("MMM d HH:mm",Locale.US).format(new Date(ts*1000L));}
    private String age(long ts){if(ts<=0)return"unknown";long sec=Math.max(0,System.currentTimeMillis()/1000L-ts);if(sec<3600)return Math.max(1,sec/60)+"m";if(sec<86400)return sec/3600+"h";return sec/86400+"d";}
    private String trim(String s,int max){if(s==null)return"";return s.length()<=max?s:s.substring(0,max-1)+"…";}
    private static final class ForumLead{final int threadId,forumId,userId;final String user,title;final long quote,time;ForumLead(int threadId,int forumId,String user,int userId,String title,long quote,long time){this.threadId=threadId;this.forumId=forumId;this.user=user;this.userId=userId;this.title=title;this.quote=quote;this.time=time;}}
}
