package com.matthayesego.duckforcetoolkit;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import org.json.JSONArray;
import org.json.JSONObject;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Faction strength provider screen. FFScouter estimates are always labeled as estimates with source/freshness. */
public class FactionStrengthActivity extends Activity {
    private static final int BG=Color.rgb(6,9,13), PANEL=Color.rgb(14,20,29), PANEL2=Color.rgb(9,14,21), BORDER=Color.rgb(45,55,69), TEXT=Color.rgb(244,246,249), MUTED=Color.rgb(154,164,178), GOLD=Color.rgb(241,194,106), BLUE=Color.rgb(88,166,255), GREEN=Color.rgb(63,185,80), RED=Color.rgb(248,81,73);
    private SecureApiKeyStore tornStore;private FFScouterKeyStore ffStore;private int factionId;private String factionName;

    @Override protected void onCreate(Bundle savedInstanceState){super.onCreate(savedInstanceState);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);tornStore=new SecureApiKeyStore(this);ffStore=new FFScouterKeyStore(this);factionId=getIntent().getIntExtra(FactionOpsActivity.EXTRA_FACTION_ID,0);factionName=getIntent().getStringExtra(FactionOpsActivity.EXTRA_FACTION_NAME);if(factionName==null||factionName.trim().isEmpty())factionName="Faction";if(ffStore.load()==null)renderSetup(null);else{showLoading();load();}}

    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private GradientDrawable rounded(int fill,int stroke,int radius){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}
    private GradientDrawable gradient(int a,int b,int stroke,int radius){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});d.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}
    private TextView text(String value,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setLineSpacing(0f,1.08f);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private Button button(String label,int stroke){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextColor(TEXT);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(rounded(PANEL2,stroke,12));return b;}
    private LinearLayout card(String title,String body,int stroke){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(17),dp(15),dp(17),dp(15));c.setBackground(rounded(PANEL,stroke,18));c.addView(text(title,18,TEXT,true));if(body!=null&&!body.isEmpty()){TextView b=text(body,13,MUTED,false);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.topMargin=dp(6);c.addView(b,p);}return c;}
    private void addCard(LinearLayout root,LinearLayout c){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.bottomMargin=dp(10);root.addView(c,p);}
    @SuppressWarnings("deprecation") private ScrollView shell(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setBackgroundColor(BG);int l=dp(16),t=dp(18),r=dp(16),b=dp(30);s.setPadding(l,t,r,b);s.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(l+i.getSystemWindowInsetLeft(),t+i.getSystemWindowInsetTop(),r+i.getSystemWindowInsetRight(),b+i.getSystemWindowInsetBottom());return i;});return s;}
    private LinearLayout root(ScrollView s){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);s.addView(r,new ScrollView.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));return r;}
    private void header(LinearLayout r,String subtitle){Button back=button("← Companion",BORDER);back.setOnClickListener(v->finish());r.addView(back,new LinearLayout.LayoutParams(dp(132),dp(44)));LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setGravity(Gravity.CENTER_HORIZONTAL);hero.setPadding(dp(18),dp(18),dp(18),dp(18));hero.setBackground(gradient(Color.rgb(20,37,55),Color.rgb(14,18,24),BLUE,22));TextView brand=text("DUCK FORCE • INTEL PROVIDER",10,BLUE,true);brand.setLetterSpacing(.13f);hero.addView(brand);TextView title=text("Faction Strength Intel",29,TEXT,true);title.setGravity(Gravity.CENTER);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);tp.topMargin=dp(5);hero.addView(title,tp);TextView sub=text(subtitle,13,MUTED,false);sub.setGravity(Gravity.CENTER);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);sp.topMargin=dp(5);hero.addView(sub,sp);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);hp.topMargin=dp(14);hp.bottomMargin=dp(14);r.addView(hero,hp);}

    private void renderSetup(String error){ScrollView s=shell();LinearLayout r=root(s);header(r,"Connect a registered FFScouter key");addCard(r,card("Why FFScouter?","Duck Force Companion uses a provider layer instead of pretending estimates are exact. FFScouter supplies battle-stat estimates, Fair Fight data, source and freshness metadata.",BLUE));
        EditText key=new EditText(this);key.setHint("Registered FFScouter API key");key.setHintTextColor(MUTED);key.setTextColor(TEXT);key.setSingleLine(true);key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);key.setPadding(dp(14),0,dp(14),0);key.setBackground(rounded(PANEL2,BORDER,12));r.addView(key,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(54)));
        Button save=button("Save FFScouter Key",GOLD);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(48));bp.topMargin=dp(8);r.addView(save,bp);Button terms=button("Open FFScouter Terms / Registration",BLUE);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(48));tp.topMargin=dp(8);r.addView(terms,tp);terms.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://ffscouter.com/"))));
        TextView note=text(error==null?"The key is encrypted on this device and stored separately from your Torn key. Registration/terms remain with FFScouter.":error,12,error==null?MUTED:RED,false);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);np.topMargin=dp(10);r.addView(note,np);
        save.setOnClickListener(v->{String entered=key.getText().toString().trim();if(entered.length()!=16||!entered.matches("[A-Za-z0-9]{16}")){note.setText("FFScouter keys are 16 alphanumeric characters.");note.setTextColor(RED);return;}try{ffStore.save(entered);showLoading();load();}catch(Exception e){note.setText("Could not securely store the FFScouter key.");note.setTextColor(RED);}});setContentView(s);s.requestApplyInsets();}

    private void showLoading(){ScrollView s=shell();LinearLayout r=root(s);header(r,"Loading estimates for "+factionName+"…");addCard(r,card("FFScouter provider","Loading the current faction roster and one batched estimate request. Estimates can be cached by FFScouter for several minutes.",BLUE));setContentView(s);s.requestApplyInsets();}

    private void load(){String ffKey=ffStore.load(),tornKey=tornStore.load();if(ffKey==null){renderSetup(null);return;}new Thread(()->{try{JSONArray roster=FactionMemberCache.load(factionId);if(roster==null){if(tornKey==null)throw new Exception("Reconnect your Torn API key to load the faction roster.");roster=TornApiClient.getJson("/faction/members",tornKey).optJSONArray("members");if(roster==null)roster=new JSONArray();FactionMemberCache.save(factionId,roster);}Map<Integer,String> names=new HashMap<>();List<Integer> ids=new ArrayList<>();for(int i=0;i<roster.length();i++){JSONObject m=roster.optJSONObject(i);if(m==null)continue;int id=m.optInt("id",0);if(id>0){ids.add(id);names.put(id,m.optString("name","Unknown"));}}JSONArray stats=FFScouterClient.getStats(ffKey,ids);List<Row> rows=new ArrayList<>();long total=0;int known=0;long newest=0;for(int i=0;i<stats.length();i++){JSONObject o=stats.optJSONObject(i);if(o==null)continue;int id=o.optInt("player_id",0);long estimate=o.isNull("bs_estimate")?0:o.optLong("bs_estimate",0);String human=o.optString("bs_estimate_human",estimate>0?human(estimate):"Unknown");double ff=o.isNull("fair_fight")?-1:o.optDouble("fair_fight",-1);long updated=o.isNull("last_updated")?0:o.optLong("last_updated",0);String source=o.optString("source","bss");if(estimate>0){known++;total+=estimate;}if(updated>newest)newest=updated;rows.add(new Row(id,names.getOrDefault(id,"Player "+id),estimate,human,ff,updated,source));}for(int id:ids){boolean found=false;for(Row row:rows)if(row.id==id){found=true;break;}if(!found)rows.add(new Row(id,names.getOrDefault(id,"Player "+id),0,"Unknown",-1,0,"bss"));}Collections.sort(rows,(a,b)->Long.compare(b.estimate,a.estimate));final long fTotal=total,fNewest=newest;final int fKnown=known,fCount=ids.size();runOnUiThread(()->render(rows,fTotal,fKnown,fCount,fNewest));}catch(Exception e){runOnUiThread(()->renderError(e.getMessage()==null?"Unable to load FFScouter estimates.":e.getMessage()));}}).start();}

    private void render(List<Row> rows,long total,int known,int count,long newest){ScrollView s=shell();LinearLayout r=root(s);header(r,factionName+" • FFScouter estimate provider");String freshness=newest>0?DateFormat.getDateTimeInstance(DateFormat.SHORT,DateFormat.SHORT).format(new Date(newest*1000L)):"Unknown";addCard(r,card("Faction estimate coverage",known+" / "+count+" members have an estimate\nKnown estimated total: "+human(total)+"\nNewest source update: "+freshness,GOLD));addCard(r,card("Estimate safety","These are scouting estimates, not exact Torn battle stats. Source and freshness are shown on every member. Unknown estimates stay unknown instead of being guessed.",BLUE));Button refresh=button("Refresh FFScouter",BLUE);refresh.setOnClickListener(v->{showLoading();load();});r.addView(refresh,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(46)));Button key=button("Change / Forget FFScouter Key",BORDER);LinearLayout.LayoutParams kp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(46));kp.topMargin=dp(8);kp.bottomMargin=dp(14);r.addView(key,kp);key.setOnClickListener(v->{ffStore.clear();renderSetup(null);});TextView label=text("MEMBER ESTIMATES",11,MUTED,true);label.setLetterSpacing(.11f);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);lp.bottomMargin=dp(8);r.addView(label,lp);for(Row row:rows){String body=row.estimate>0?"Estimated battle stats: "+row.human+(row.ff>=0?"\nFair Fight: "+String.format(Locale.US,"%.2f",row.ff):"")+"\nSource: "+sourceLabel(row.source)+(row.updated>0?" • Updated "+DateFormat.getDateTimeInstance(DateFormat.SHORT,DateFormat.SHORT).format(new Date(row.updated*1000L)):" • Freshness unknown"):"No current FFScouter battle-stat estimate.\nSource: FFScouter • confidence unknown";addCard(r,card(row.name,body,row.estimate>0?GREEN:BORDER));}TextView footer=text("Provider: FFScouter • Duck Force Companion v0.9.2",11,MUTED,false);footer.setGravity(Gravity.CENTER);r.addView(footer);setContentView(s);s.requestApplyInsets();}
    private void renderError(String message){ScrollView s=shell();LinearLayout r=root(s);header(r,"Provider unavailable");addCard(r,card("FFScouter could not load",message,RED));Button reset=button("Review FFScouter Key",GOLD);reset.setOnClickListener(v->renderSetup(message));r.addView(reset,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(48)));setContentView(s);s.requestApplyInsets();}
    private static String sourceLabel(String source){if("premium".equalsIgnoreCase(source))return"FFScouter premium spy";if("spies".equalsIgnoreCase(source))return"Faction spy via FFScouter";return"FFScouter public BSS";}
    private static String human(long v){if(v>=1_000_000_000_000L)return String.format(Locale.US,"%.2ft",v/1_000_000_000_000d);if(v>=1_000_000_000L)return String.format(Locale.US,"%.2fb",v/1_000_000_000d);if(v>=1_000_000L)return String.format(Locale.US,"%.2fm",v/1_000_000d);if(v>=1_000L)return String.format(Locale.US,"%.1fk",v/1_000d);return Long.toString(v);}
    private static final class Row{final int id;final String name;final long estimate;final String human;final double ff;final long updated;final String source;Row(int id,String name,long estimate,String human,double ff,long updated,String source){this.id=id;this.name=name;this.estimate=estimate;this.human=human;this.ff=ff;this.updated=updated;this.source=source;}}
}
