package com.matthayesego.duckforcetoolkit;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;

/** Everyday member launchpad. Leadership is additive; this screen is useful to every faction member. */
public class MemberCenterActivity extends Activity {
    @Override protected void onCreate(Bundle b){super.onCreate(b);PushNotifications.syncIfReady(this);int player=currentPlayerId();if(player>0)PremiumAccess.refresh(this,player);render();}
    @Override protected void onResume(){super.onResume();render();}
    private void render(){ScrollView s=TornFcaUi.shell(this);LinearLayout r=TornFcaUi.root(this,s);TornFcaUi.header(this,r,"More","Member Center","Your daily faction tools, training resources, personal participation and faction community in one place.");addLaunch(r,"TODAY","My Day","Bars, cooldowns, refills, personal OC, chain, current war, faction standing and what to do next.",TornFcaUi.GREEN,MemberDailyActivity.class,null);addLaunch(r,"FACTION","Faction Overview","Your faction status and member-safe faction information.",TornFcaUi.GOLD,MemberFactionActivity.class,null);addLaunch(r,"DIRECTORY","Faction Directory","Search the current roster and open member-safe status cards without leadership analytics.",TornFcaUi.BLUE,MemberDirectoryActivity.class,null);addLaunch(r,"RESOURCES","Faction Resources","Faction-local onboarding checklist, custom guides and shortcuts to the member tools you need most.",TornFcaUi.GOLD,FactionResourcesActivity.class,null);addLaunch(r,"TRAINING","Training Center","Universal training guides plus your current faction's private rules and custom guide library.",TornFcaUi.PURPLE,TrainingCenterActivity.class,null);addLaunch(r,"PROGRESS","My Training Progress","Track your own battle-stat gains and Xanax use from a faction-specific local baseline, then compare them with current faction expectations.",TornFcaUi.GREEN,TrainingProgressActivity.class,null);addLaunch(r,"WAR","My War","Current personal ranked-war participation plus your recent completed-war history.",TornFcaUi.RED,MemberWarActivity.class,null);addLaunch(r,"OC","My Organized Crime","Your personal OC assignment/readiness view. Leadership-wide OC data remains permission-gated.",TornFcaUi.PURPLE,null,FeatureRouterActivity.TARGET_OC);addLaunch(r,"CHAIN","Chain Status","Current faction chain status and participation context.",TornFcaUi.BLUE,null,FeatureRouterActivity.TARGET_CHAIN);addLaunch(r,"COMMUNITY","Faction Chat",CommunityBackendClient.isConfigured()?"Chat with authenticated members of your faction inside TornFCA.":"Faction chat client is installed; community backend connection is pending.",TornFcaUi.BLUE,FactionChatActivity.class,null);addLaunch(r,"ALERTS","Notification Inbox","Keep important TornFCA alerts available after they leave Android's notification shade.",TornFcaUi.GOLD,NotificationInboxActivity.class,null);int player=currentPlayerId();boolean premium=PremiumAccess.has(this,player,PremiumAccess.PERSONAL_INSIGHTS);addLaunch(r,premium?"PREMIUM ACTIVE":"PREMIUM","Premium Insights",premium?"Your 30-day personal activity, ranked-war trend and local payout history.":"See the Premium personal analytics experience and what it adds beyond the free member core.",TornFcaUi.GOLD,PremiumInsightsActivity.class,null);setContentView(s);s.requestApplyInsets();}
    private void addLaunch(LinearLayout r,String eye,String title,String body,int accent,Class<?> activity,String feature){LinearLayout c=TornFcaUi.card(this,eye,title,body,accent);Button b=TornFcaUi.button(this,"Open "+title,accent);b.setOnClickListener(v->{if(activity!=null)startActivity(new Intent(this,activity));else{Intent i=new Intent(this,FeatureRouterActivity.class);i.putExtra(FeatureRouterActivity.EXTRA_TARGET,feature);startActivity(i);}});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,TornFcaUi.dp(this,46));p.topMargin=TornFcaUi.dp(this,10);c.addView(b,p);TornFcaUi.add(this,r,c);}
    private int currentPlayerId(){String key=new SecureApiKeyStore(this).load();if(key==null)return 0;AuthSession hot=TornApiClient.cachedSession(key);if(hot!=null)return hot.playerId;FactionScopeCache.Scope scope=FactionScopeCache.load(this,key);return scope==null?0:scope.playerId;}
}
