package com.matthayesego.duckforcetoolkit;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;

/** Player-facing plan screen. Entitlements are backend-verified when the premium backend is configured. */
public class PremiumPreviewActivity extends Activity {
    @Override protected void onCreate(Bundle b){super.onCreate(b);int player=currentPlayerId();if(player>0)PremiumAccess.refresh(this,player);render();}
    @Override protected void onResume(){super.onResume();render();}
    private void render(){ScrollView s=TornFcaUi.shell(this);LinearLayout r=TornFcaUi.root(this,s);TornFcaUi.header(this,r,"More","TornFCA Premium","Free stays useful. Premium adds personal power and convenience—not basic faction participation.");int player=currentPlayerId();boolean premium=PremiumAccess.has(this,player,PremiumAccess.PERSONAL_INSIGHTS);String state=premium?"PREMIUM ACTIVE":"FREE";String detail=premium?PremiumEntitlementStore.summary(this):(PremiumBackendClient.isConfigured()?"Your account currently has the complete free member core.":"You have the complete free member core. Premium billing is not enabled in this beta build.");TornFcaUi.add(this,r,TornFcaUi.card(this,"YOUR PLAN",state,detail,premium?TornFcaUi.GOLD:TornFcaUi.GREEN));TornFcaUi.addSection(this,r,"Free — always useful");TornFcaUi.add(this,r,TornFcaUi.card(this,"MEMBER CORE","Included for every member","My Day • faction overview • My War and recent war history • personal OC • chain status • faction announcements • standard notification categories • faction chat when the community service is connected.",TornFcaUi.GREEN));TornFcaUi.add(this,r,TornFcaUi.card(this,"LEADERSHIP","Permissions, not a paywall","Faction leadership tools remain controlled by the member's real faction permissions. TornFCA Premium is not required simply to lead or administer a faction.",TornFcaUi.GREEN));TornFcaUi.addSection(this,r,"Premium");LinearLayout insights=TornFcaUi.card(this,"PERSONAL INSIGHTS","Your 30-day trends","A working personal analytics view for recent outgoing activity, ranked-war participation, faction war results and local WarPay receipts.",TornFcaUi.GOLD);Button open=TornFcaUi.button(this,premium?"Open Premium Insights":"Preview Premium Insights",TornFcaUi.GOLD);open.setOnClickListener(v->startActivity(new Intent(this,PremiumInsightsActivity.class)));LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,TornFcaUi.dp(this,46));op.topMargin=TornFcaUi.dp(this,9);insights.addView(open,op);TornFcaUi.add(this,r,insights);TornFcaUi.add(this,r,TornFcaUi.card(this,"SMART ALERTS","More control over your attention","Advanced war alert lead times and future personal automation beyond the standard free notification set.",TornFcaUi.GOLD));TornFcaUi.add(this,r,TornFcaUi.card(this,"PERSONALIZATION","Make TornFCA yours","Additional dashboard customization, saved views and premium convenience options without hiding core faction functionality behind a purchase.",TornFcaUi.GOLD));TornFcaUi.add(this,r,TornFcaUi.card(this,"ENTITLEMENT","Account-based","Premium follows your Torn player ID and is verified server-side when the Premium backend is connected. Local developer simulation is never treated as a real purchase.",TornFcaUi.BLUE));setContentView(s);s.requestApplyInsets();}
    private int currentPlayerId(){String key=new SecureApiKeyStore(this).load();if(key==null)return 0;AuthSession hot=TornApiClient.cachedSession(key);if(hot!=null)return hot.playerId;FactionScopeCache.Scope sc=FactionScopeCache.load(this,key);return sc==null?0:sc.playerId;}
}
