package com.matthayesego.duckforcetoolkit;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Toast;

import java.text.DateFormat;
import java.util.Date;

public class SettingsActivity extends Activity {
    @Override protected void onCreate(Bundle b){super.onCreate(b);render();}
    @Override protected void onResume(){super.onResume();render();}
    private void render(){ScrollView s=TornFcaUi.shell(this);LinearLayout r=TornFcaUi.root(this,s);TornFcaUi.header(this,r,"More","Settings","Notifications, account security, integrations and privacy controls.");
        LinearLayout notifications=TornFcaUi.card(this,"NOTIFICATIONS","Alerts & Notification Inbox","Choose war, OC, chain, faction, chat and personal alerts. Android permission stays under your control.",TornFcaUi.BLUE);Button manage=TornFcaUi.button(this,"Manage Notifications",TornFcaUi.BLUE);manage.setOnClickListener(v->startActivity(new Intent(this,NotificationSettingsActivity.class)));LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,TornFcaUi.dp(this,46));np.topMargin=TornFcaUi.dp(this,10);notifications.addView(manage,np);TornFcaUi.add(this,r,notifications);
        SecureApiKeyStore store=new SecureApiKeyStore(this);long expiry=store.persistedUntilMillis();String mode=expiry>0?"Encrypted on this device until "+DateFormat.getDateTimeInstance(DateFormat.MEDIUM,DateFormat.SHORT).format(new Date(expiry))+".":"Session-only. The API key is not retained for a future app session.";LinearLayout account=TornFcaUi.card(this,"ACCOUNT & SECURITY","API key retention",mode,TornFcaUi.GREEN);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);addRetentionButton(row,"Session",false,30,0);addRetentionButton(row,"7d",true,7,1);addRetentionButton(row,"30d",true,30,2);addRetentionButton(row,"90d",true,90,3);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,TornFcaUi.dp(this,44));rp.topMargin=TornFcaUi.dp(this,10);account.addView(row,rp);TornFcaUi.add(this,r,account);
        String key=store.load();boolean ff=key!=null&&FFScouterClient.hasConsent(this,key),ts=TornStatsClient.hasConsent(this);LinearLayout integrations=TornFcaUi.card(this,"INTEGRATIONS","Intelligence providers","FFScouter: "+(ff?"enabled":"disabled")+" • TornStats: "+(ts?"enabled":"disabled")+". Enablement is still performed only after reviewing the provider's terms inside intelligence tools.",TornFcaUi.PURPLE);if(ff||ts){Button disable=TornFcaUi.button(this,"Disable External Intelligence Providers",TornFcaUi.RED);disable.setOnClickListener(v->{if(key!=null)FFScouterClient.setConsent(this,key,false);TornStatsClient.setConsent(this,false);Toast.makeText(this,"External provider access disabled.",Toast.LENGTH_SHORT).show();render();});LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,TornFcaUi.dp(this,46));ip.topMargin=TornFcaUi.dp(this,10);integrations.addView(disable,ip);}TornFcaUi.add(this,r,integrations);
        int player=currentPlayerId();String premium=player>0&&PremiumEntitlementStore.hasPremium(this,player)?"Premium active":"Free plan";LinearLayout plan=TornFcaUi.card(this,"PLAN","TornFCA "+premium,"Core member and leadership functionality is not paywalled. Premium adds personal automation, advanced alert tuning, deeper history and convenience features.",TornFcaUi.GOLD);Button planButton=TornFcaUi.button(this,"View Plan",TornFcaUi.GOLD);planButton.setOnClickListener(v->startActivity(new Intent(this,PremiumPreviewActivity.class)));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,TornFcaUi.dp(this,46));pp.topMargin=TornFcaUi.dp(this,10);plan.addView(planButton,pp);TornFcaUi.add(this,r,plan);
        TornFcaUi.add(this,r,TornFcaUi.card(this,"PRIVACY","Local data","Notification history and preferences stay on this device. Torn API keys remain session-only unless you explicitly choose encrypted retention. External intelligence providers remain opt-in.",TornFcaUi.GREEN));
        Button logout=TornFcaUi.button(this,"Log Out / Change API Key",TornFcaUi.RED);logout.setOnClickListener(v->logout());r.addView(logout,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,TornFcaUi.dp(this,50)));setContentView(s);s.requestApplyInsets();}
    private void addRetentionButton(LinearLayout row,String label,boolean persist,int days,int index){Button b=TornFcaUi.button(this,label,TornFcaUi.BORDER);b.setOnClickListener(v->applyRetention(persist,days));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,TornFcaUi.dp(this,44),1f);if(index>0)p.leftMargin=TornFcaUi.dp(this,6);row.addView(b,p);}
    private void applyRetention(boolean persist,int days){try{SecureApiKeyStore store=new SecureApiKeyStore(this);String key=store.load();if(key==null||key.isBlank()){Toast.makeText(this,"No active API key is available.",Toast.LENGTH_SHORT).show();return;}SecureApiKeyStore.prepareNextSave(persist,days);store.save(key);Toast.makeText(this,persist?("API key encrypted for "+days+" days."):"API key changed to session-only.",Toast.LENGTH_SHORT).show();render();}catch(Exception e){Toast.makeText(this,"Unable to change key retention.",Toast.LENGTH_LONG).show();}}
    private int currentPlayerId(){String key=new SecureApiKeyStore(this).load();if(key==null)return 0;AuthSession hot=TornApiClient.cachedSession(key);if(hot!=null)return hot.playerId;FactionScopeCache.Scope sc=FactionScopeCache.load(this,key);return sc==null?0:sc.playerId;}
    private void logout(){new SecureApiKeyStore(this).clear();FactionScopeCache.clear(this);TornApiClient.clearMemoryCache();FactionMemberCache.clear();DeveloperPreviewStore.clear(this);PremiumEntitlementStore.clear(this);NotificationInboxStore.clear(this);Intent i=new Intent(this,AccessGateActivity.class);i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK);startActivity(i);finish();}
}
