package com.matthayesego.duckforcetoolkit;

import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.ImageDecoder;
import android.graphics.Typeface;
import android.graphics.drawable.Animatable;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.Drawable;
import android.graphics.drawable.GradientDrawable;
import android.os.Build;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.CheckBox;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.Spinner;
import android.widget.TextView;

import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.ByteBuffer;

/** Public TornFCA shell. Existing v0.9 functionality remains underneath this brand/theme layer. */
public class TornFcaActivity extends V098CompanionActivity {
    private static final long AVATAR_REFRESH_MS=6L*60L*60L*1000L;
    private volatile boolean avatarRefreshInFlight=false;
    private View observedIdentityRoot;

    @Override public void setContentView(View view){super.setContentView(view);ViewGroup root=findViewById(android.R.id.content);if(root!=null){if(!isCommandActivity())TornFcaBrand.apply(this,root);installIdentityRepair(root);repairFactionIdentity(root);addApiRequirementNotice(root);addKeyRetentionControls(root);retargetBankingCards(root);restoreProfileAvatar(root);}primeProviderConsent();}
    @Override protected void onResume(){super.onResume();ViewGroup root=findViewById(android.R.id.content);if(root!=null){if(!isCommandActivity())TornFcaBrand.apply(this,root);installIdentityRepair(root);repairFactionIdentity(root);addApiRequirementNotice(root);addKeyRetentionControls(root);retargetBankingCards(root);restoreProfileAvatar(root);}primeProviderConsent();refreshPremiumEntitlement();}
    @Override public void startActivity(Intent intent){Intent routed=TornFcaBrand.retarget(this,intent);if(TornFcaCommandRuntime.enabled()&&routed!=null&&routed.getComponent()!=null){String name=routed.getComponent().getClassName();if(TornFcaActivity.class.getName().equals(name)||TornFcaCurrentActivity.class.getName().equals(name)||V098CompanionActivity.class.getName().equals(name)||V095CompanionActivity.class.getName().equals(name)){Intent home=TornFcaCommandRuntime.homeIntent(this,"Home");home.addFlags(routed.getFlags());routed=home;}}super.startActivity(routed);}
    private boolean isCommandActivity(){return this instanceof BetaCommandActivity;}
    private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}

    private TextView findLoginTitle(View root){TextView title=findText(root,"Sign in to TornFCA");if(title==null)title=findText(root,"Sign in to Duck Force");if(title==null)title=findText(root,"Connect your Torn account");return title;}
    private void installIdentityRepair(ViewGroup root){
        if(observedIdentityRoot==root)return;
        observedIdentityRoot=root;
        root.post(()->{
            if(isFinishing())return;
            try{repairFactionIdentity(root);}catch(Exception ignored){}
        });
    }
    private void repairFactionIdentity(View root){String key=new SecureApiKeyStore(this).load();if(key==null||key.isBlank())return;AuthSession hot=TornApiClient.cachedSession(key);FactionScopeCache.Scope scope=hot==null?FactionScopeCache.load(this,key):null;String faction=hot!=null?hot.factionName:scope==null?"":scope.factionName;String position=hot!=null?hot.position:scope==null?"":scope.position;if(faction==null||faction.isBlank())return;if(DeveloperPreviewStore.isMemberPreview(this))position="Member Preview";repairFactionText(root,faction.trim(),position==null?"":position.trim());}
    private void repairFactionText(View view,String faction,String position){if(view instanceof TextView){TextView t=(TextView)view;String raw=t.getText()==null?"":t.getText().toString();if(raw.startsWith("Duck Force  •  "))t.setText(faction+"  •  "+(position.isEmpty()?"Member":position));else if(raw.startsWith("Duck Force • ")&&raw.length()<80)t.setText(faction+" • "+(position.isEmpty()?"Member":position));else if("Duck Force has no current or upcoming ranked war.".equals(raw))t.setText(faction+" has no current or upcoming ranked war.");}if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++)repairFactionText(g.getChildAt(i),faction,position);}}

    private void addApiRequirementNotice(View root){TextView title=findLoginTitle(root);if(title==null||!(title.getParent() instanceof LinearLayout))return;LinearLayout card=(LinearLayout)title.getParent();for(int i=0;i<card.getChildCount();i++)if("tornfca-api-requirement".equals(card.getChildAt(i).getTag()))return;FactionTheme theme=FactionTheme.forContext(this);TextView notice=new TextView(this);notice.setTag("tornfca-api-requirement");notice.setText("TORN API KEY USE • LIMITED ACCESS RECOMMENDED\n\nData Storage: device-local caches/preferences; shared faction records only for cloud features you use.\nData Sharing: intended faction/authorized workflows; moderation/operator access only where described in Legal & Privacy.\nPurpose: faction tools, sync, notifications, moderation/support, aggregate usage counts and Premium verification.\nKey Storage & Sharing: session-only by default, or encrypted locally if you choose 7/30/90 days. The key is sent over HTTPS to Torn and may be sent request-by-request to TornFCA backends for identity/permission checks; TornFCA backends are designed not to persist client API keys. FFScouter/TornStats are separate opt-ins.\nKey Access Level: Limited Access recommended; Full Access is not required.\n\nTap here to review the full Legal & Privacy disclosure before connecting.");notice.setTextSize(11.5f);notice.setTextColor(Color.rgb(224,232,241));notice.setTypeface(Typeface.create("sans-serif",Typeface.NORMAL));notice.setLineSpacing(0f,1.10f);notice.setPadding(dp(13),dp(12),dp(13),dp(12));notice.setClickable(true);notice.setFocusable(true);notice.setOnClickListener(v->startActivity(new Intent(this,LegalActivity.class)));GradientDrawable bg=new GradientDrawable();bg.setColor(Color.rgb(8,18,25));bg.setCornerRadius(dp(13));bg.setStroke(dp(1),theme.accent);notice.setBackground(bg);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.topMargin=dp(12);p.bottomMargin=dp(3);card.addView(notice,Math.min(2,card.getChildCount()),p);}
    private void addKeyRetentionControls(View root){TextView title=findLoginTitle(root);if(title==null||!(title.getParent() instanceof LinearLayout))return;LinearLayout card=(LinearLayout)title.getParent();for(int i=0;i<card.getChildCount();i++)if("tornfca-key-retention".equals(card.getChildAt(i).getTag()))return;LinearLayout box=new LinearLayout(this);box.setTag("tornfca-key-retention");box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),dp(10),dp(12),dp(10));GradientDrawable bg=new GradientDrawable();bg.setColor(Color.rgb(8,13,20));bg.setCornerRadius(dp(12));bg.setStroke(dp(1),Color.rgb(45,55,69));box.setBackground(bg);CheckBox remember=new CheckBox(this);remember.setText("Save API key on this device");remember.setTextColor(Color.rgb(244,246,249));remember.setTextSize(13f);remember.setChecked(false);box.addView(remember);TextView helper=new TextView(this);helper.setText("Off: kept only for this app session. On: encrypted locally and automatically removed after the selected period.");helper.setTextColor(Color.rgb(154,164,178));helper.setTextSize(11.5f);box.addView(helper);Spinner days=new Spinner(this);String[] choices=new String[]{"7 days","30 days","90 days"};ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,choices);adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);days.setAdapter(adapter);days.setSelection(1);days.setEnabled(false);LinearLayout.LayoutParams dpv=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(48));dpv.topMargin=dp(5);box.addView(days,dpv);Runnable sync=()->{int selected=days.getSelectedItemPosition()==0?7:days.getSelectedItemPosition()==2?90:30;SecureApiKeyStore.prepareNextSave(remember.isChecked(),selected);};remember.setOnCheckedChangeListener((buttonView,isChecked)->{days.setEnabled(isChecked);sync.run();});days.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){@Override public void onItemSelected(android.widget.AdapterView<?> parent,View view,int position,long id){sync.run();}@Override public void onNothingSelected(android.widget.AdapterView<?> parent){sync.run();}});SecureApiKeyStore.prepareNextSave(false,30);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.topMargin=dp(9);p.bottomMargin=dp(4);card.addView(box,Math.min(3,card.getChildCount()),p);}

    private void retargetBankingCards(View root){if(root instanceof TextView){TextView t=(TextView)root;if("Banking".equals(t.getText()==null?"":t.getText().toString())){View card=findClickableAncestor(t);if(card!=null){card.setOnClickListener(v->{Intent i=new Intent(this,FeatureRouterActivity.class);i.putExtra(FeatureRouterActivity.EXTRA_TARGET,FeatureRouterActivity.TARGET_BANKING);startActivity(i);});}}}if(root instanceof ViewGroup){ViewGroup g=(ViewGroup)root;for(int i=0;i<g.getChildCount();i++)retargetBankingCards(g.getChildAt(i));}}
    private View findClickableAncestor(View start){View v=start;while(v!=null){if(v.isClickable())return v;if(!(v.getParent() instanceof View))break;v=(View)v.getParent();}return null;}

    private void restoreProfileAvatar(ViewGroup root){ImageView avatar=findHeaderAvatar(root);if(avatar==null)return;String key=new SecureApiKeyStore(this).load();if(key==null||key.isBlank())return;int playerId=0;AuthSession hot=TornApiClient.cachedSession(key);if(hot!=null)playerId=hot.playerId;if(playerId<=0){FactionScopeCache.Scope scope=FactionScopeCache.load(this,key);if(scope!=null)playerId=scope.playerId;}if(playerId<=0)return;File cached=avatarFile(playerId);if(cached.exists()){Drawable local=decodeAvatarFile(cached);if(local!=null)applyAvatar(avatar,local);if(local!=null&&System.currentTimeMillis()-cached.lastModified()<AVATAR_REFRESH_MS)return;}if(avatarRefreshInFlight)return;avatarRefreshInFlight=true;final int id=playerId;new Thread(()->{try{JSONObject rootJson=TornApiClient.getJson("/user/"+id+"/profile",key);JSONObject profile=rootJson.optJSONObject("profile");if(profile==null)profile=rootJson;String image=firstNonBlank(profile.optString("image",""),profile.optString("profile_image",""));image=normalizeImageUrl(image);if(image.isEmpty())return;AvatarDownload result=downloadAvatar(image);if(result==null||result.drawable==null)return;try(FileOutputStream out=new FileOutputStream(avatarFile(id))){out.write(result.bytes);}runOnUiThread(()->{ViewGroup current=findViewById(android.R.id.content);ImageView currentAvatar=current==null?null:findHeaderAvatar(current);if(currentAvatar!=null)applyAvatar(currentAvatar,result.drawable);});}catch(Exception ignored){}finally{avatarRefreshInFlight=false;}},"TornFCA-ProfileAvatar").start();}
    private void applyAvatar(ImageView target,Drawable drawable){target.setPadding(0,0,0,0);target.setScaleType(ImageView.ScaleType.CENTER_CROP);target.setImageDrawable(drawable);if(drawable instanceof Animatable)((Animatable)drawable).start();}
    private String firstNonBlank(String a,String b){if(a!=null&&!a.trim().isEmpty()&&!"null".equalsIgnoreCase(a.trim()))return a.trim();if(b!=null&&!b.trim().isEmpty()&&!"null".equalsIgnoreCase(b.trim()))return b.trim();return"";}
    private String normalizeImageUrl(String raw){if(raw==null)return"";String value=raw.trim();if(value.isEmpty()||"null".equalsIgnoreCase(value))return"";if(value.startsWith("//"))value="https:"+value;else if(value.startsWith("/"))value="https://www.torn.com"+value;else if(value.startsWith("http://"))value="https://"+value.substring("http://".length());try{URL url=new URL(value);return"https".equalsIgnoreCase(url.getProtocol())?value:"";}catch(Exception e){return"";}}
    private File avatarFile(int playerId){return new File(getCacheDir(),"torn-profile-"+playerId+".img");}
    private Drawable decodeAvatarFile(File file){try(FileInputStream in=new FileInputStream(file);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return decodeDrawable(out.toByteArray());}catch(Exception e){return null;}}
    private Drawable decodeDrawable(byte[] bytes)throws Exception{if(bytes==null||bytes.length==0)return null;if(Build.VERSION.SDK_INT>=28){ImageDecoder.Source source=ImageDecoder.createSource(ByteBuffer.wrap(bytes));return ImageDecoder.decodeDrawable(source);}Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length);return bitmap==null?null:new BitmapDrawable(getResources(),bitmap);}
    private AvatarDownload downloadAvatar(String value)throws Exception{URL url=new URL(value);if(!"https".equalsIgnoreCase(url.getProtocol()))return null;HttpURLConnection c=(HttpURLConnection)url.openConnection();try{c.setConnectTimeout(8000);c.setReadTimeout(12000);c.setUseCaches(true);c.setInstanceFollowRedirects(true);c.setRequestProperty("User-Agent","Mozilla/5.0 (Android) TornFCA/"+TornFcaBrand.VERSION);c.setRequestProperty("Accept","image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8");c.setRequestProperty("Referer","https://www.torn.com/");int code=c.getResponseCode();if(code<200||code>=300)return null;try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] buffer=new byte[8192];int n,total=0;while((n=in.read(buffer))!=-1){total+=n;if(total>8*1024*1024)return null;out.write(buffer,0,n);}byte[] bytes=out.toByteArray();Drawable drawable=decodeDrawable(bytes);return drawable==null?null:new AvatarDownload(drawable,bytes);}}finally{c.disconnect();}}
    private ImageView findHeaderAvatar(View view){if(view instanceof ImageView&&"tornfca-profile-avatar".equals(view.getTag()))return(ImageView)view;if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++){ImageView found=findHeaderAvatar(g.getChildAt(i));if(found!=null)return found;}}return null;}
    private void primeProviderConsent(){String key=new SecureApiKeyStore(this).load();if(key!=null&&!key.isBlank())FFScouterClient.hasConsent(this,key);}
    private void refreshPremiumEntitlement(){String key=new SecureApiKeyStore(this).load();if(key==null||key.isBlank()||!PremiumBackendClient.isConfigured())return;int playerId=0;FactionScopeCache.Scope scope=FactionScopeCache.load(this,key);if(scope!=null)playerId=scope.playerId;AuthSession hot=TornApiClient.cachedSession(key);if(playerId<=0&&hot!=null)playerId=hot.playerId;if(playerId<=0)return;PremiumBackendClient.refreshAsync(this,playerId);}
    private TextView findText(View view,String needle){if(view instanceof TextView){TextView t=(TextView)view;if(needle.equals(t.getText()==null?"":t.getText().toString()))return t;}if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++){TextView found=findText(g.getChildAt(i),needle);if(found!=null)return found;}}return null;}
    private static final class AvatarDownload{final Drawable drawable;final byte[] bytes;AvatarDownload(Drawable drawable,byte[] bytes){this.drawable=drawable;this.bytes=bytes;}}
}
