package com.matthayesego.duckforcetoolkit;

import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.ViewTreeObserver;
import android.widget.LinearLayout;
import android.widget.TextView;

/** v0.9.x navigation/polish layer. Keeps developer tooling invisible except for the footer triple-tap. */
public class V095CompanionActivity extends V090CompanionActivity {
    private static final int BG=Color.rgb(6,9,13),PANEL=Color.rgb(12,18,26),BORDER=Color.rgb(38,49,64),TEXT=Color.rgb(244,246,249),MUTED=Color.rgb(145,156,172),GOLD=Color.rgb(241,194,106),BLUE=Color.rgb(88,166,255),GREEN=Color.rgb(63,185,80),RED=Color.rgb(248,81,73);
    private TextView navHome,navFaction;

    @Override public void setContentView(View view){boolean home=containsIgnoreCase(view,"Welcome back,");super.setContentView(view);stampCurrent(view);if(home){installBottomNavigation();attachCurrentObserver(view);}}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private GradientDrawable rounded(int fill,int stroke,int radius){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}
    private GradientDrawable gradient(int a,int b,int stroke,int radius){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{a,b});d.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}

    private void installBottomNavigation(){ViewGroup host=findViewById(android.R.id.content);if(host==null||host.getChildCount()==0)return;View current=host.getChildAt(0);if("v096-frame".equals(current.getTag()))return;host.removeView(current);LinearLayout frame=new LinearLayout(this);frame.setTag("v096-frame");frame.setOrientation(LinearLayout.VERTICAL);frame.setBackgroundColor(BG);frame.addView(current,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1f));LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setGravity(Gravity.CENTER);nav.setPadding(dp(5),dp(6),dp(5),dp(5));nav.setElevation(dp(10));nav.setBackground(gradient(Color.rgb(16,23,33),Color.rgb(8,12,18),BORDER,18));navHome=navItem("⌂","Home",GOLD,()->{clickExact(current,"Home");select(navHome);});navFaction=navItem("◆","Faction",MUTED,()->{clickExact(current,"Faction");select(navFaction);});TextView war=navItem("⚔","War",MUTED,()->openFeature(FeatureRouterActivity.TARGET_WAR));TextView chain=navItem("⛓","Chain",MUTED,()->openFeature(FeatureRouterActivity.TARGET_CHAIN));TextView more=navItem("⋯","More",MUTED,()->startActivity(new Intent(this,MoreActivity.class)));nav.addView((View)navHome.getParent(),navParams());nav.addView((View)navFaction.getParent(),navParams());nav.addView((View)war.getParent(),navParams());nav.addView((View)chain.getParent(),navParams());nav.addView((View)more.getParent(),navParams());int baseBottom=dp(5);nav.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(dp(5),dp(6),dp(5),baseBottom+i.getSystemWindowInsetBottom());return i;});frame.addView(nav,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(72)));host.addView(frame,new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));nav.requestApplyInsets();}

    private TextView navItem(String icon,String label,int color,Runnable action){LinearLayout item=new LinearLayout(this);item.setOrientation(LinearLayout.VERTICAL);item.setGravity(Gravity.CENTER);item.setClickable(true);item.setFocusable(true);TextView symbol=new TextView(this);symbol.setText(icon);symbol.setTextColor(color);symbol.setTextSize(21);symbol.setGravity(Gravity.CENTER);item.addView(symbol,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(28)));TextView text=new TextView(this);text.setText(label);text.setTextColor(color);text.setTextSize(10);text.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));text.setGravity(Gravity.CENTER);item.addView(text,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(22)));item.setOnClickListener(v->action.run());return text;}
    private LinearLayout.LayoutParams navParams(){return new LinearLayout.LayoutParams(0,dp(58),1f);}
    private void select(TextView selected){ViewGroup host=findViewById(android.R.id.content);if(host==null)return;setBottomColor(host,"Home",selected==navHome?GOLD:MUTED);setBottomColor(host,"Faction",selected==navFaction?GOLD:MUTED);}
    private void setBottomColor(View root,String exact,int color){TextView t=findExactInBottom(root,exact);if(t!=null){t.setTextColor(color);if(t.getParent() instanceof ViewGroup){ViewGroup p=(ViewGroup)t.getParent();if(p.getChildCount()>0&&p.getChildAt(0) instanceof TextView)((TextView)p.getChildAt(0)).setTextColor(color);}}}
    private TextView findExactInBottom(View root,String exact){if(root instanceof TextView&&exact.contentEquals(((TextView)root).getText()))return(TextView)root;if(root instanceof ViewGroup){ViewGroup g=(ViewGroup)root;for(int i=g.getChildCount()-1;i>=0;i--){TextView f=findExactInBottom(g.getChildAt(i),exact);if(f!=null)return f;}}return null;}

    private void attachCurrentObserver(View root){if(root==null||"v096-observed".equals(root.getTag()))return;root.setTag("v096-observed");root.getViewTreeObserver().addOnGlobalLayoutListener(()->polishCurrent(root));polishCurrent(root);}
    private void polishCurrent(View root){stampCurrent(root);hideDeveloperConsole(root);renamePrivateTools(root);ensureStrengthIntel(root);}
    private void stampCurrent(View view){if(view instanceof TextView){TextView t=(TextView)view;CharSequence raw=t.getText();if(raw!=null){String v=raw.toString().replace("v0.8.0","v0.9.6").replace("v0.9.0","v0.9.6").replace("v0.9.1","v0.9.6").replace("v0.9.2","v0.9.6").replace("v0.9.3","v0.9.6").replace("v0.9.4","v0.9.6").replace("v0.9.5","v0.9.6");if(!v.equals(raw.toString()))t.setText(v);}}if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++)stampCurrent(g.getChildAt(i));}}
    private void hideDeveloperConsole(View root){TextView t=findContainingIgnoreCase(root,"developer console");if(t!=null&&t.getParent() instanceof View)((View)t.getParent()).setVisibility(View.GONE);}
    private void renamePrivateTools(View root){TextView t=findExact(root,"OWNER / DEVELOPER");if(t!=null&&t.getVisibility()==View.VISIBLE)t.setText("PRIVATE TOOLS");}

    private void ensureStrengthIntel(View root){if(containsIgnoreCase(root,"Faction Strength Intel"))return;TextView section=findExact(root,"FACTION OVERVIEW");if(section==null||!(section.getParent() instanceof LinearLayout))return;LinearLayout parent=(LinearLayout)section.getParent();LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(16),dp(13),dp(16),dp(13));card.setBackground(gradient(Color.rgb(18,34,50),Color.rgb(10,16,24),BLUE,18));card.setClickable(true);card.setFocusable(true);TextView eyebrow=new TextView(this);eyebrow.setText("FFSCOUTER • PLAYER-OWNED KEY");eyebrow.setTextColor(BLUE);eyebrow.setTextSize(9);eyebrow.setTypeface(Typeface.DEFAULT,Typeface.BOLD);eyebrow.setLetterSpacing(.09f);card.addView(eyebrow);TextView title=new TextView(this);title.setText("Faction Strength Intel  →");title.setTextColor(TEXT);title.setTextSize(18);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);tp.topMargin=dp(4);card.addView(title,tp);TextView body=new TextView(this);body.setText("Connect FFScouter once • estimates • Fair Fight • freshness");body.setTextColor(MUTED);body.setTextSize(12);card.addView(body);card.setOnClickListener(v->openFeature(FeatureRouterActivity.TARGET_STRENGTH));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(104));p.bottomMargin=dp(10);parent.addView(card,Math.min(parent.indexOfChild(section)+1,parent.getChildCount()),p);}

    private boolean clickExact(View root,String exact){TextView t=findExact(root,exact);if(t!=null){t.performClick();return true;}return false;}
    private TextView findExact(View view,String exact){if(view instanceof TextView){CharSequence raw=((TextView)view).getText();if(raw!=null&&exact.equals(raw.toString()))return(TextView)view;}if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++){TextView f=findExact(g.getChildAt(i),exact);if(f!=null)return f;}}return null;}
    private TextView findContainingIgnoreCase(View view,String needle){String n=needle.toLowerCase();if(view instanceof TextView){CharSequence raw=((TextView)view).getText();if(raw!=null&&raw.toString().toLowerCase().contains(n))return(TextView)view;}if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++){TextView f=findContainingIgnoreCase(g.getChildAt(i),needle);if(f!=null)return f;}}return null;}
    private boolean containsIgnoreCase(View view,String needle){return findContainingIgnoreCase(view,needle)!=null;}
    private void openFeature(String target){Intent i=new Intent(this,FeatureRouterActivity.class);i.putExtra(FeatureRouterActivity.EXTRA_TARGET,target);startActivity(i);}
}
