package com.matthayesego.duckforcetoolkit;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import org.json.JSONArray;
import org.json.JSONObject;

import java.text.DateFormat;
import java.util.Date;

/** Ranked-war hub with live gating, completed-war drill-down and leadership payout access. */
public class WarCenterActivity extends Activity {
    private static final int BG=Color.rgb(5,8,12),PANEL=Color.rgb(12,18,26),PANEL2=Color.rgb(8,13,20),BORDER=Color.rgb(36,47,61),TEXT=Color.rgb(246,248,251),MUTED=Color.rgb(145,155,169),GOLD=Color.rgb(241,190,86),BLUE=Color.rgb(82,153,235),GREEN=Color.rgb(76,190,102),RED=Color.rgb(239,88,82);
    private SecureApiKeyStore keyStore;
    private int factionId;
    private String factionName,position;
    private boolean factionApi;

    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);keyStore=new SecureApiKeyStore(this);factionId=getIntent().getIntExtra(FactionOpsActivity.EXTRA_FACTION_ID,0);factionName=getIntent().getStringExtra(FactionOpsActivity.EXTRA_FACTION_NAME);position=getIntent().getStringExtra(DeveloperConsoleActivity.EXTRA_POSITION);factionApi=getIntent().getBooleanExtra(FactionOpsActivity.EXTRA_FACTION_API,false);if(factionName==null||factionName.isBlank())factionName="Faction";if(position==null)position="Member";showLoading();load();}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private GradientDrawable rounded(int fill,int stroke,int radius){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}
    private GradientDrawable gradient(int a,int b,int stroke,int radius){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});d.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}
    private TextView text(String value,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setLineSpacing(0f,1.08f);if(bold)t.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));return t;}
    private TextView eyebrow(String value,int color){TextView t=text(value,9.5f,color,true);t.setLetterSpacing(.12f);return t;}
    private Button button(String value,int accent){Button b=new Button(this);b.setText(value);b.setAllCaps(false);b.setTextColor(TEXT);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(rounded(PANEL2,accent,13));return b;}
    @SuppressWarnings("deprecation") private ScrollView shell(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setClipToPadding(false);s.setBackgroundColor(BG);int l=dp(18),t=dp(14),r=dp(18),bt=dp(28);s.setPadding(l,t,r,bt);s.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(l+i.getSystemWindowInsetLeft(),t+i.getSystemWindowInsetTop(),r+i.getSystemWindowInsetRight(),bt+i.getSystemWindowInsetBottom());return i;});return s;}
    private LinearLayout root(ScrollView s){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);s.addView(r,new ScrollView.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));return r;}
    private LinearLayout card(int accent){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(16),dp(18),dp(16));c.setBackground(gradient(PANEL,PANEL2,accent==Color.TRANSPARENT?BORDER:accent,20));return c;}
    private void add(LinearLayout root,LinearLayout c){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.bottomMargin=dp(12);root.addView(c,p);}
    private void header(LinearLayout r){Button back=button("← Companion",BORDER);back.setOnClickListener(v->finish());r.addView(back,new LinearLayout.LayoutParams(dp(132),dp(44)));TextView eye=eyebrow("DUCK FORCE • WAR CENTER",GOLD);LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);ep.topMargin=dp(18);r.addView(eye,ep);r.addView(text("War Center",32,TEXT,true));TextView sub=text("Live status, opponent intelligence, participation and completed ranked-war history.",13,MUTED,false);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);sp.topMargin=dp(5);sp.bottomMargin=dp(18);r.addView(sub,sp);}
    private void showLoading(){ScrollView s=shell();LinearLayout r=root(s);header(r);LinearLayout c=card(BORDER);c.addView(eyebrow("LOADING",GOLD));c.addView(text("Building your war picture…",20,TEXT,true));c.addView(text("Checking current ranked-war status and recent war history from Torn.",13,MUTED,false));add(r,c);setContentView(s);s.requestApplyInsets();}
    private void load(){String key=keyStore.load();if(key==null||key.isBlank()){renderError("Reconnect your Torn API key to use War Center.");return;}new Thread(()->{try{if(factionId<=0){JSONObject f=TornApiClient.getJson("/user/faction",key).optJSONObject("faction");if(f!=null)factionId=f.optInt("id",0);}WarStatus current=WarStatus.from(TornApiClient.getJson("/faction/wars",key),factionId);JSONArray history=TornApiClient.getJson("/faction/"+factionId+"/rankedwars?limit=8",key).optJSONArray("rankedwars");if(history==null)history=new JSONArray();JSONArray finalHistory=history;runOnUiThread(()->render(current,finalHistory));}catch(Exception e){renderError(e.getMessage()==null?"Unable to load war data.":e.getMessage());}}).start();}
    private void render(WarStatus current,JSONArray history){ScrollView s=shell();LinearLayout r=root(s);header(r);long now=System.currentTimeMillis()/1000L;add(r,currentCard(current,now));if(current.present&&(current.isLive(now)||current.isUpcoming(now))){LinearLayout tools=new LinearLayout(this);tools.setOrientation(LinearLayout.HORIZONTAL);Button intel=button("Opponent Intel",BLUE);intel.setEnabled(current.opponentFactionId>0);intel.setOnClickListener(v->openStrength(current.opponentFactionId,current.opponent));tools.addView(intel,new LinearLayout.LayoutParams(0,dp(48),1f));Button part=button("Participation",GREEN);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(0,dp(48),1f);pp.leftMargin=dp(10);tools.addView(part,pp);part.setOnClickListener(v->openParticipation());LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);tp.bottomMargin=dp(16);r.addView(tools,tp);}if(AccessPolicy.isLeaderPosition(position)){LinearLayout payout=card(GOLD);payout.addView(eyebrow("LEADERSHIP",GOLD));payout.addView(text("War Payout",20,TEXT,true));payout.addView(text("Calculate payouts and reopen locally saved receipts from completed wars.",13,MUTED,false));Button open=button("Open Payout Calculator",GOLD);LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(48));op.topMargin=dp(12);payout.addView(open,op);open.setOnClickListener(v->openPayout());add(r,payout);}TextView hist=eyebrow("RECENT RANKED WARS",MUTED);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);hp.topMargin=dp(4);hp.bottomMargin=dp(8);r.addView(hist,hp);if(history.length()==0){LinearLayout none=card(BORDER);none.addView(text("No completed war history returned",18,TEXT,true));add(r,none);}else{for(int i=0;i<history.length();i++){JSONObject w=history.optJSONObject(i);if(w!=null)add(r,historyCard(w));}}TextView footer=text("TornFCA • War Center",10.5f,MUTED,false);footer.setGravity(Gravity.CENTER);LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);fp.topMargin=dp(8);fp.bottomMargin=dp(8);r.addView(footer,fp);setContentView(s);s.requestApplyInsets();}
    private LinearLayout currentCard(WarStatus w,long now){int accent=!w.present?GREEN:w.isLive(now)?RED:w.isUpcoming(now)?GOLD:MUTED;LinearLayout c=card(accent);String eye=!w.present?"CURRENT STATUS":w.isLive(now)?"LIVE RANKED WAR":w.isUpcoming(now)?"UPCOMING RANKED WAR":"LATEST STATUS";c.addView(eyebrow(eye,accent));String title=!w.present?"No Current Ranked War":w.isLive(now)?"War In Progress":w.isUpcoming(now)?"War Scheduled":"Latest War Ended";TextView h=text(title,25,TEXT,true);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);hp.topMargin=dp(6);c.addView(h,hp);String body;if(!w.present)body="Your faction is currently between ranked wars. Recent results are below.";else if(w.isLive(now))body="vs "+w.opponent+"\nScore: "+w.ourScore+" – "+w.opponentScore+(w.target>0?" • Target "+w.target:"")+"\nElapsed: "+WarStatus.duration(now-w.start);else if(w.isUpcoming(now))body="vs "+w.opponent+(w.target>0?" • Target "+w.target:"")+"\nStarts in "+WarStatus.duration(w.start-now);else body="vs "+w.opponent+" • Final "+w.ourScore+" – "+w.opponentScore;c.addView(text(body,14,MUTED,false));if(w.simulated)c.addView(text("Developer simulation only — no Torn faction state is modified.",11.5f,GOLD,true));return c;}
    private LinearLayout historyCard(JSONObject w){int winner=w.isNull("winner")?0:w.optInt("winner",0);int warId=w.optInt("id",0);JSONArray fs=w.optJSONArray("factions");String opponent="Opponent";int our=0,their=0;for(int j=0;fs!=null&&j<fs.length();j++){JSONObject f=fs.optJSONObject(j);if(f==null)continue;if(f.optInt("id",0)==factionId)our=f.optInt("score",0);else{opponent=f.optString("name",opponent);their=f.optInt("score",0);}}String result=winner==0?"DRAW":winner==factionId?"WIN":"LOSS";int accent="WIN".equals(result)?GREEN:"LOSS".equals(result)?RED:MUTED;LinearLayout c=card(Color.TRANSPARENT);LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);TextView name=text(opponent,18,TEXT,true);top.addView(name,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1f));TextView badge=text(result,11,accent,true);badge.setGravity(Gravity.CENTER);badge.setBackground(rounded(Color.rgb(15,20,27),accent,10));top.addView(badge,new LinearLayout.LayoutParams(dp(60),dp(30)));c.addView(top);long end=w.optLong("end",0);String date=end>0?DateFormat.getDateInstance(DateFormat.MEDIUM).format(new Date(end*1000L)):"Unknown date";c.addView(text("Final "+our+" – "+their+" • "+date+" • War #"+warId,12.5f,MUTED,false));Button details=button("View War Details",BLUE);LinearLayout.LayoutParams dpv=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(44));dpv.topMargin=dp(9);c.addView(details,dpv);details.setOnClickListener(v->openHistory(warId));return c;}
    private void openHistory(int warId){Intent i=new Intent(this,WarHistoryDetailActivity.class);i.putExtra(WarHistoryDetailActivity.EXTRA_WAR_ID,warId);i.putExtra(WarHistoryDetailActivity.EXTRA_FACTION_ID,factionId);String key=keyStore.load();AuthSession cached=key==null?null:TornApiClient.cachedSession(key);if(cached!=null){i.putExtra(WarHistoryDetailActivity.EXTRA_PLAYER_ID,cached.playerId);i.putExtra(WarHistoryDetailActivity.EXTRA_PLAYER_NAME,cached.playerName);}startActivity(i);}
    private void openParticipation(){Intent i=new Intent(this,FactionOpsActivity.class);i.putExtra(FactionOpsActivity.EXTRA_MODE,FactionOpsActivity.MODE_WAR);putScope(i);startActivity(i);}
    private void openStrength(int id,String name){if(id<=0)return;Intent i=new Intent(this,FactionStrengthActivity.class);i.putExtra(FactionOpsActivity.EXTRA_FACTION_ID,id);i.putExtra(FactionOpsActivity.EXTRA_FACTION_NAME,name);i.putExtra(FactionStrengthActivity.EXTRA_SCOUTING_TARGET,true);startActivity(i);}
    private void openPayout(){Intent i=new Intent(this,WarPayoutActivity.class);putScope(i);startActivity(i);}
    private void putScope(Intent i){i.putExtra(FactionOpsActivity.EXTRA_FACTION_ID,factionId);i.putExtra(FactionOpsActivity.EXTRA_FACTION_NAME,factionName);i.putExtra(FactionOpsActivity.EXTRA_FACTION_API,factionApi);i.putExtra(DeveloperConsoleActivity.EXTRA_POSITION,position);}
    private void renderError(String message){runOnUiThread(()->{ScrollView s=shell();LinearLayout r=root(s);header(r);LinearLayout c=card(RED);c.addView(eyebrow("WAR DATA UNAVAILABLE",RED));c.addView(text(message,14,TEXT,false));Button retry=button("Retry",GOLD);retry.setOnClickListener(v->{showLoading();load();});LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(48));rp.topMargin=dp(12);c.addView(retry,rp);add(r,c);setContentView(s);s.requestApplyInsets();});}
}
