package com.matthayesego.duckforcetoolkit;

import android.app.Activity;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONObject;

import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;

/** Leadership-only calculation workflow. Does not move faction funds. */
public class WarPayoutActivity extends Activity {
    private static final int BG=Color.rgb(5,8,12),PANEL=Color.rgb(12,18,26),PANEL2=Color.rgb(8,13,20),BORDER=Color.rgb(36,47,61),TEXT=Color.rgb(246,248,251),MUTED=Color.rgb(145,155,169),GOLD=Color.rgb(241,190,86),BLUE=Color.rgb(82,153,235),GREEN=Color.rgb(76,190,102),RED=Color.rgb(239,88,82);
    private SecureApiKeyStore keyStore;
    private int factionId;
    private String factionName,position;
    private JSONArray history=new JSONArray();
    private JSONObject selectedReport;
    private boolean splitByScore=false;

    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);keyStore=new SecureApiKeyStore(this);factionId=getIntent().getIntExtra(FactionOpsActivity.EXTRA_FACTION_ID,0);factionName=getIntent().getStringExtra(FactionOpsActivity.EXTRA_FACTION_NAME);position=getIntent().getStringExtra(DeveloperConsoleActivity.EXTRA_POSITION);if(factionName==null||factionName.isBlank())factionName="Faction";if(position==null)position="Member";if(!AccessPolicy.isLeaderPosition(position)){renderError("War Payout is currently restricted to faction leadership.");return;}showLoading("Loading completed ranked wars…");loadHistory();}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private GradientDrawable rounded(int fill,int stroke,int radius){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}
    private GradientDrawable gradient(int a,int b,int stroke,int radius){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});d.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}
    private TextView text(String value,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setLineSpacing(0f,1.08f);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private TextView eyebrow(String value,int color){TextView t=text(value,9.5f,color,true);t.setLetterSpacing(.12f);return t;}
    private Button button(String value,int accent){Button b=new Button(this);b.setText(value);b.setAllCaps(false);b.setTextColor(TEXT);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(rounded(PANEL2,accent,13));return b;}
    private EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(MUTED);e.setTextColor(TEXT);e.setTextSize(15);e.setSingleLine(true);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setPadding(dp(14),0,dp(14),0);e.setBackground(rounded(PANEL2,BORDER,12));return e;}
    @SuppressWarnings("deprecation") private ScrollView shell(){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setClipToPadding(false);s.setBackgroundColor(BG);int l=dp(18),t=dp(14),r=dp(18),b=dp(28);s.setPadding(l,t,r,b);s.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(l+i.getSystemWindowInsetLeft(),t+i.getSystemWindowInsetTop(),r+i.getSystemWindowInsetRight(),b+i.getSystemWindowInsetBottom());return i;});return s;}
    private LinearLayout root(ScrollView s){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);s.addView(r,new ScrollView.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));return r;}
    private LinearLayout card(int accent){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(16),dp(18),dp(16));c.setBackground(gradient(PANEL,PANEL2,accent==Color.TRANSPARENT?BORDER:accent,20));return c;}
    private void add(LinearLayout root,LinearLayout c){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.bottomMargin=dp(12);root.addView(c,p);}
    private void header(LinearLayout r){Button back=button("← War Center",BORDER);back.setOnClickListener(v->finish());r.addView(back,new LinearLayout.LayoutParams(dp(140),dp(44)));TextView e=eyebrow("LEADERSHIP • WAR PAYOUT",GOLD);LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);ep.topMargin=dp(18);r.addView(e,ep);r.addView(text("War Payout",31,TEXT,true));TextView sub=text("Use official ranked-war reports to calculate a reviewable payout. No faction funds are moved from this screen.",13,MUTED,false);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);sp.topMargin=dp(5);sp.bottomMargin=dp(18);r.addView(sub,sp);}
    private void showLoading(String msg){ScrollView s=shell();LinearLayout r=root(s);header(r);LinearLayout c=card(BORDER);c.addView(eyebrow("LOADING",GOLD));c.addView(text(msg,19,TEXT,true));add(r,c);setContentView(s);s.requestApplyInsets();}
    private void loadHistory(){String key=keyStore.load();if(key==null){renderError("Reconnect your Torn API key first.");return;}new Thread(()->{try{if(factionId<=0){JSONObject f=TornApiClient.getJson("/user/faction",key).optJSONObject("faction");if(f!=null)factionId=f.optInt("id",0);}JSONArray h=TornApiClient.getJson("/faction/"+factionId+"/rankedwars?limit=8",key).optJSONArray("rankedwars");history=h==null?new JSONArray():h;runOnUiThread(this::renderWarPicker);}catch(Exception e){renderError(e.getMessage()==null?"Unable to load ranked-war history.":e.getMessage());}}).start();}
    private void renderWarPicker(){ScrollView s=shell();LinearLayout r=root(s);header(r);LinearLayout note=card(GOLD);note.addView(eyebrow("STEP 1",GOLD));note.addView(text("Choose a completed war",20,TEXT,true));note.addView(text("The selected war report provides official member attacks and war score for the calculation.",13,MUTED,false));add(r,note);if(history.length()==0){LinearLayout none=card(BORDER);none.addView(text("No completed ranked wars returned.",17,TEXT,true));add(r,none);}for(int i=0;i<history.length();i++){JSONObject w=history.optJSONObject(i);if(w==null)continue;int id=w.optInt("id",0);JSONArray fs=w.optJSONArray("factions");String opponent="Opponent";int our=0,their=0,winner=w.isNull("winner")?0:w.optInt("winner",0);for(int j=0;fs!=null&&j<fs.length();j++){JSONObject f=fs.optJSONObject(j);if(f==null)continue;if(f.optInt("id",0)==factionId)our=f.optInt("score",0);else{opponent=f.optString("name",opponent);their=f.optInt("score",0);}}String result=winner==factionId?"WIN":winner==0?"DRAW":"LOSS";int accent="WIN".equals(result)?GREEN:"LOSS".equals(result)?RED:MUTED;LinearLayout c=card(Color.TRANSPARENT);c.addView(eyebrow(result+" • WAR #"+id,accent));c.addView(text("vs "+opponent,19,TEXT,true));c.addView(text("Final "+our+" – "+their,13,MUTED,false));Button use=button("Use This War",accent);LinearLayout.LayoutParams up=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(46));up.topMargin=dp(10);c.addView(use,up);use.setOnClickListener(v->loadReport(id));add(r,c);}setContentView(s);s.requestApplyInsets();}
    private void loadReport(int warId){showLoading("Loading official war #"+warId+" report…");String key=keyStore.load();new Thread(()->{try{JSONObject root=TornApiClient.getJson("/faction/"+warId+"/rankedwarreport",key);JSONObject report=root.optJSONObject("rankedwarreport");if(report==null)throw new Exception("Ranked-war report was empty.");selectedReport=report;runOnUiThread(this::renderCalculator);}catch(Exception e){renderError(e.getMessage()==null?"Unable to load war report.":e.getMessage());}}).start();}
    private void renderCalculator(){ScrollView s=shell();LinearLayout r=root(s);header(r);JSONObject ours=findOurFaction(selectedReport);if(ours==null){renderError("Duck Force was not found in this report.");return;}LinearLayout summary=card(GREEN);summary.addView(eyebrow("STEP 2 • WAR #"+selectedReport.optInt("id",0),GREEN));summary.addView(text("Official participation loaded",20,TEXT,true));summary.addView(text(ours.optInt("attacks",0)+" faction attacks • "+ours.optJSONArray("members").length()+" participating members",13,MUTED,false));add(r,summary);LinearLayout settings=card(GOLD);settings.addView(eyebrow("PAYOUT SETTINGS",GOLD));EditText pool=field("Total payout pool (e.g. 500000000)");LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(52));fp.topMargin=dp(10);settings.addView(pool,fp);EditText minHits=field("Minimum attacks required");minHits.setText("1");LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(52));mp.topMargin=dp(9);settings.addView(minHits,mp);Button mode=button(splitByScore?"Split Method: War Score":"Split Method: Attacks",BLUE);LinearLayout.LayoutParams mop=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(48));mop.topMargin=dp(9);settings.addView(mode,mop);mode.setOnClickListener(v->{splitByScore=!splitByScore;mode.setText(splitByScore?"Split Method: War Score":"Split Method: Attacks");});Button calc=button("Calculate Payout",GOLD);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(50));cp.topMargin=dp(10);settings.addView(calc,cp);add(r,settings);LinearLayout resultHost=new LinearLayout(this);resultHost.setOrientation(LinearLayout.VERTICAL);r.addView(resultHost,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));calc.setOnClickListener(v->calculate(ours,pool,minHits,resultHost));TextView foot=text("Calculation only • Banking and faction funds remain untouched",10.5f,MUTED,false);foot.setGravity(Gravity.CENTER);r.addView(foot);setContentView(s);s.requestApplyInsets();}
    private JSONObject findOurFaction(JSONObject report){JSONArray fs=report==null?null:report.optJSONArray("factions");for(int i=0;fs!=null&&i<fs.length();i++){JSONObject f=fs.optJSONObject(i);if(f!=null&&f.optInt("id",0)==factionId)return f;}return null;}
    private void calculate(JSONObject ours,EditText poolField,EditText minField,LinearLayout host){host.removeAllViews();long pool;int minHits;try{String raw=poolField.getText().toString().replace(",","").trim();pool=(long)Double.parseDouble(raw);minHits=Integer.parseInt(minField.getText().toString().trim());if(pool<=0||minHits<0)throw new Exception();}catch(Exception e){Toast.makeText(this,"Enter a valid payout pool and minimum attacks.",Toast.LENGTH_SHORT).show();return;}JSONArray members=ours.optJSONArray("members");List<Share> rows=new ArrayList<>();double totalMetric=0;for(int i=0;members!=null&&i<members.length();i++){JSONObject m=members.optJSONObject(i);if(m==null)continue;int attacks=m.optInt("attacks",0);if(attacks<minHits)continue;double metric=splitByScore?Math.max(0,m.optDouble("score",0)):attacks;if(metric<=0)continue;Share row=new Share(m.optInt("id",0),m.optString("name","Member"),attacks,m.optDouble("score",0),metric);rows.add(row);totalMetric+=metric;}if(rows.isEmpty()||totalMetric<=0){Toast.makeText(this,"No members qualify with those settings.",Toast.LENGTH_SHORT).show();return;}long assigned=0;for(int i=0;i<rows.size();i++){Share row=rows.get(i);if(i==rows.size()-1)row.payout=pool-assigned;else{row.payout=(long)Math.floor(pool*(row.metric/totalMetric));assigned+=row.payout;}}Collections.sort(rows,(a,b)->Long.compare(b.payout,a.payout));LinearLayout summary=card(GREEN);summary.addView(eyebrow("CALCULATED",GREEN));summary.addView(text(money(pool)+" payout pool",20,TEXT,true));summary.addView(text(rows.size()+" qualifying members • split by "+(splitByScore?"war score":"attacks")+" • minimum "+minHits+" attacks",12.5f,MUTED,false));Button copy=button("Copy Payout List",GREEN);LinearLayout.LayoutParams cop=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(46));cop.topMargin=dp(10);summary.addView(copy,cop);host.addView(summary,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));StringBuilder paste=new StringBuilder("War #").append(selectedReport.optInt("id",0)).append(" payout — ").append(money(pool)).append("\n");int rank=1;for(Share row:rows){LinearLayout c=card(Color.TRANSPARENT);c.addView(text(rank+". "+row.name,17,TEXT,true));c.addView(text(money(row.payout)+" • "+row.attacks+" attacks • score "+String.format(Locale.US,"%.2f",row.score),12.5f,MUTED,false));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.topMargin=dp(10);host.addView(c,p);paste.append(rank).append(". ").append(row.name).append(" — ").append(money(row.payout)).append("\n");rank++;}String out=paste.toString().trim();copy.setOnClickListener(v->copy(out));}
    private static String money(long value){return "$"+NumberFormat.getIntegerInstance(Locale.US).format(value);}
    private void copy(String value){ClipboardManager c=(ClipboardManager)getSystemService(Context.CLIPBOARD_SERVICE);if(c!=null){c.setPrimaryClip(ClipData.newPlainText("War Payout",value));Toast.makeText(this,"Payout list copied.",Toast.LENGTH_SHORT).show();}}
    private void renderError(String message){runOnUiThread(()->{ScrollView s=shell();LinearLayout r=root(s);header(r);LinearLayout c=card(RED);c.addView(eyebrow("PAYOUT UNAVAILABLE",RED));c.addView(text(message,14,TEXT,false));Button retry=button("Back to War List",GOLD);retry.setOnClickListener(v->loadHistory());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(48));p.topMargin=dp(12);c.addView(retry,p);add(r,c);setContentView(s);s.requestApplyInsets();});}
    private static final class Share{final int id;final String name;final int attacks;final double score,metric;long payout;Share(int id,String name,int attacks,double score,double metric){this.id=id;this.name=name;this.attacks=attacks;this.score=score;this.metric=metric;}}
}
